### ISSUE TITLE
The jar snapshot doesn't run

### ISSUE THREAD

**Issue by neerolyte** [WebGoat/WebGoat#108]
Java version: 1.7.0_79 - OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1).

First run results in an unintuitive extraction error:
```
$ java -jar webgoat-container-7.0-SNAPSHOT-war-exec.jar                         
Exception in thread "main" java.lang.Exception: FATAL: impossible to create directories:.extract/webapps
        at org.apache.tomcat.maven.runner.Tomcat7Runner.extract(Tomcat7Runner.java:586)
        at org.apache.tomcat.maven.runner.Tomcat7Runner.run(Tomcat7Runner.java:204)
        at org.apache.tomcat.maven.runner.Tomcat7RunnerCli.main(Tomcat7RunnerCli.java:212)
```

Second run produces other errors:
```
$ java -jar webgoat-container-7.0-SNAPSHOT-war-exec.jar                         
Oct 06, 2015 7:44:55 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Oct 06, 2015 7:44:55 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Oct 06, 2015 7:44:55 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.47
Oct 06, 2015 7:44:55 PM org.apache.catalina.startup.ContextConfig init
SEVERE: Exception fixing docBase for context [/WebGoat]
java.io.FileNotFoundException: ....../.extract/webapps/WebGoat.war (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:215)
        at java.util.zip.ZipFile.<init>(ZipFile.java:145)
        at java.util.jar.JarFile.<init>(JarFile.java:154)
        at java.util.jar.JarFile.<init>(JarFile.java:91)
        at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
        at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:99)
        at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
        at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
        at org.apache.catalina.startup.ExpandWar.expand(ExpandWar.java:113)
        at org.apache.catalina.startup.ContextConfig.fixDocBase(ContextConfig.java:722)
        at org.apache.catalina.startup.ContextConfig.init(ContextConfig.java:843)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:387)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:110)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:139)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Oct 06, 2015 7:44:55 PM org.apache.catalina.core.StandardContext resourcesStart
SEVERE: Error starting static Resources
java.lang.IllegalArgumentException: Invalid or unreadable WAR file : ...../.extract/webapps/WebGoat.war
        at org.apache.naming.resources.WARDirContext.setDocBase(WARDirContext.java:133)
        at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:5055)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5235)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Oct 06, 2015 7:44:55 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error in resourceStart()
Oct 06, 2015 7:44:55 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error getConfigured
Oct 06, 2015 7:44:55 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/WebGoat] startup failed due to previous errors
Oct 06, 2015 7:44:55 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
```

The .extract directory appears to only contain the directory skeleton:
```
$ find .extract/
.extract/
.extract/webapps
.extract/conf
.extract/logs
.extract/logs/access_log.2015-10-06
.extract/work
.extract/work/Tomcat
.extract/work/Tomcat/localhost
.extract/work/Tomcat/localhost/WebGoat
.extract/temp
```

**Comment by nbaars** [comment]
Same error when running the executable war.

**Comment by span** [comment]
Just cloned the project and can confirm it working for both cases on OS X with `java version "1.8.0_45" Java(TM) SE Runtime Environment (build 1.8.0_45-b14) Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)`

**Comment by nbaars** [comment]
Ok great, closing the issue

**Comment by nbaars** [comment]
Issue is back. @dougmorato can you check? seems like the  `<tomcat7-maven-plugin.version>2.2</tomcat7-maven-plugin.version>` is back at 2.2. While fixing this issue I changed it to 2.1 because there are some issues with 2.2.

**Comment by dougmorato** [comment]
2.2 really has a bug: Info: https://issues.apache.org/jira/browse/MTOMCAT-211

I updated plugin version to 2.3-snapshot, which fixes the bug

Related info:
Info: https://issues.apache.org/jira/browse/MTOMCAT-211
https://fisheye6.atlassian.com/changelog/tomcat?cs=1539956
https://fisheye6.atlassian.com/changelog/tomcat?cs=1539209
