### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by omega71044** [WebGoat/WebGoat#1174]
Hello, 

An error message appeared after running the following command in KaliLinux 

┌──(kali㉿kali)-[~/Downloads]
└─$ java -jar webgoat-server-8.2.2.jar
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/owasp/webgoat/StartWebGoat has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
Please assist 
I updated apt update and java

**Comment by aolle** [comment]
Hello,

the log says that JDK 15 or above is needed and you're executing it with JDK 11. We recommend JDK 17 (LTS).

If you updated java to an upper version with apt ensure that the java command you're executing is the desired one.

**Comment by omega71044** [comment]
Thanks for the prompt response I got this error 
┌──(kali㉿kali)-[~/Downloads]
└─$ java -jar webgoat-server-8.2.2.jar --server.address=0.0.0.0                            255 ⨯
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
12:21:23.424 [main] INFO org.owasp.webgoat.StartWebGoat - Starting WebGoat with args: --server.address=0.0.0.0
12:21:23.436 [main] ERROR org.owasp.webgoat.StartWebGoat - Port 127.0.0.1:8080 is already in use
Port 127.0.0.1:8080 is in use. Use environment value WEBGOAT_PORT to set a different value.

**Comment by aolle** [comment]
It seems that you already have something listening on 8080 port.

Try changing the listen port, like:

WEBGOAT_PORT=8081 java -jar webgoat-server-8.2.2.jar --server.address=0.0.0.0

and WebGoat will be located at: http://localhost:8081/WebGoat

**Comment by omega71044** [comment]
Thank you a bunch
