### ISSUE TITLE
webgoat-integration-tests module fails for "Closing the fork 1 after not saying Good Bye."

### ISSUE THREAD

**Issue by lolptdr** [WebGoat/WebGoat#1181]
When I run the basic build command on WebGoat (939f860dddda748a22c1b7666727d2bf6576e47b), the webgoat-integration-tests fails for the first fork not properly exiting (or at least that's how I understand it). Once I set `<reuseForks>false</reuseForks>` in the `<configuration>` node for the maven-surefire-plugin plugin of the webgoat-integration-tests/pom.xml file, then the project gets farther but it still fails.

There was no webgoat-integration-tests/target/surefire-reports directory and no dump files that I saw (or at least none in this project after the build failed).

Is this expected or what configurations do I need to set to not allow this happen? Is `<reuseForks>false</reuseForks>` inhibiting speed of the project's build?

```text
$ mvn clean install -X
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/dalgona/Documents/apache-maven-3.6.3
Java version: 17.0.1, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "11.5", arch: "x86_64", family: "mac"
...
[DEBUG] Forking command line: /bin/sh -c cd /Users/dalgona/Projects/webgoat2/webgoat-integration-tests && /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.desktop/java.beans=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED -jar /Users/dalgona/Projects/webgoat2/webgoat-integration-tests/target/surefire/surefirebooter12266034394328310271.jar /Users/dalgona/Projects/webgoat2/webgoat-integration-tests/target/surefire 2021-12-12T23-33-54_759-jvmRun1 surefire15013301180628529893tmp surefire_2012876620233641452816tmp
[DEBUG] Fork Channel [1] connected to the client.
[INFO] Running org.owasp.webgoat.SessionManagementTest

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.5.4)

[DEBUG] Closing the fork 1 after not saying Good Bye.
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for WebGoat Parent Pom 8.2.3-SNAPSHOT:
[INFO] 
[INFO] WebGoat Parent Pom ................................. SUCCESS [  1.677 s]
[INFO] webgoat-container .................................. SUCCESS [ 23.778 s]
[INFO] webgoat-plugins-parent ............................. SUCCESS [  0.193 s]
[INFO] bypass-restrictions ................................ SUCCESS [ 15.415 s]
[INFO] challenge .......................................... SUCCESS [ 10.156 s]
[INFO] client-side-filtering .............................. SUCCESS [ 15.282 s]
[INFO] cross-site-scripting ............................... SUCCESS [  4.090 s]
[INFO] html-tampering ..................................... SUCCESS [  0.960 s]
[INFO] http-basics ........................................ SUCCESS [  0.866 s]
[INFO] cia ................................................ SUCCESS [ 14.725 s]
[INFO] chrome-dev-tools ................................... SUCCESS [ 14.592 s]
[INFO] http-proxies ....................................... SUCCESS [  3.267 s]
[INFO] insecure-login ..................................... SUCCESS [  0.791 s]
[INFO] insecure-deserialization ........................... SUCCESS [  8.112 s]
[INFO] jwt ................................................ SUCCESS [ 16.054 s]
[INFO] sql-injection ...................................... SUCCESS [ 16.260 s]
[INFO] xxe ................................................ SUCCESS [ 16.430 s]
[INFO] idor ............................................... SUCCESS [  1.363 s]
[INFO] vulnerable-components .............................. SUCCESS [  2.487 s]
[INFO] webgoat-introduction ............................... SUCCESS [  0.706 s]
[INFO] webwolf-introduction ............................... SUCCESS [  0.882 s]
[INFO] auth-bypass ........................................ SUCCESS [  0.878 s]
[INFO] missing-function-ac ................................ SUCCESS [ 14.227 s]
[INFO] csrf ............................................... SUCCESS [ 13.908 s]
[INFO] password-reset ..................................... SUCCESS [  1.253 s]
[INFO] ssrf ............................................... SUCCESS [  1.345 s]
[INFO] secure-passwords ................................... SUCCESS [  1.114 s]
[INFO] webgoat-lesson-template ............................ SUCCESS [  1.077 s]
[INFO] crypto ............................................. SUCCESS [  3.088 s]
[INFO] path-traversal ..................................... SUCCESS [ 16.386 s]
[INFO] spoof-cookie ....................................... SUCCESS [  3.724 s]
[INFO] logging ............................................ SUCCESS [  0.999 s]
[INFO] hijack-session ..................................... SUCCESS [  3.381 s]
[INFO] webgoat-server ..................................... SUCCESS [  2.142 s]
[INFO] webwolf ............................................ SUCCESS [ 13.032 s]
[INFO] webgoat-integration-tests .......................... FAILURE [ 51.637 s]
[INFO] webgoat-all-in-one-docker .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:56 min
[INFO] Finished at: 2021-12-12T23:38:42-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project webgoat-integration-tests: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/dalgona/Projects/webgoat2/webgoat-integration-tests/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/dalgona/Projects/webgoat2/webgoat-integration-tests && /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.desktop/java.beans=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED -jar /Users/dalgona/Projects/webgoat2/webgoat-integration-tests/target/surefire/surefirebooter12266034394328310271.jar /Users/dalgona/Projects/webgoat2/webgoat-integration-tests/target/surefire 2021-12-12T23-33-54_759-jvmRun1 surefire15013301180628529893tmp surefire_2012876620233641452816tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/dalgona/Projects/webgoat2/webgoat-integration-tests && /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.desktop/java.beans=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED -jar /Users/dalgona/Projects/webgoat2/webgoat-integration-tests/target/surefire/surefirebooter12266034394328310271.jar /Users/dalgona/Projects/webgoat2/webgoat-integration-tests/target/surefire 2021-12-12T23-33-54_759-jvmRun1 surefire15013301180628529893tmp surefire_2012876620233641452816tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:748)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

**Comment by zubcevic** [comment]
Can you check with Maven 3.8.*?
There should be no issues on Windows, Mac or Linux as these are all in the automated build workflow as well

**Comment by nbaars** [comment]
We saw the same issue, it is indeed related to the Maven version.

**Comment by zubcevic** [comment]
I saw this on my MacBook with 8 vCPU's when I already reserved 6 vCPU's for RedHat Code Ready Container environment. 
In that case the integration test with just 2 vCPU remaining only worked in the slow mode with forkCount 1 and reuse forks false. If CRC is turned off and I have the default cpu and mem capacity it is no problem

**Comment by lolptdr** [comment]
Sorry for the late reply, I tried with Maven 3.8.4 and got the same error:

```text
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project webgoat-integration-tests: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/jting/Projects/webgoat2/webgoat-integration-tests/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/jting/Projects/webgoat2/webgoat-integration-tests && /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.desktop/java.beans=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED -jar /Users/jting/Projects/webgoat2/webgoat-integration-tests/target/surefire/surefirebooter537013819382701727.jar /Users/jting/Projects/webgoat2/webgoat-integration-tests/target/surefire 2021-12-23T08-22-56_614-jvmRun1 surefire2164180184300935390tmp surefire_204078104412260386668tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/jting/Projects/webgoat2/webgoat-integration-tests && /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.desktop/java.beans=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED -jar /Users/jting/Projects/webgoat2/webgoat-integration-tests/target/surefire/surefirebooter537013819382701727.jar /Users/jting/Projects/webgoat2/webgoat-integration-tests/target/surefire 2021-12-23T08-22-56_614-jvmRun1 surefire2164180184300935390tmp surefire_204078104412260386668tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:748)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :webgoat-integration-tests
$ mvn -v
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /Users/jting/Documents/apache-maven-3.8.4
Java version: 17.0.1, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "11.5", arch: "x86_64", family: "mac"
```
