### ISSUE TITLE
Cannot serialize session attribute

### ISSUE THREAD

**Issue by dougmorato** [WebGoat/WebGoat#123]
Whenever the __tomcat shutdown__ goal is called, I get a stacktrace for a serialization issue

```Java
Oct 24, 2015 8:25:54 PM org.apache.catalina.session.StandardSession writeObject
WARNING: Cannot serialize session attribute org.springframework.web.context.request.ServletRequestAttributes.DESTRUCTION_CALLBACK.scopedTarget.labelDebugger for session 06B9ABC8B7145B9C57D838A59A747DCD
java.io.NotSerializableException: org.owasp.webgoat.session.LabelDebugger
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.catalina.session.StandardSession.writeObject(StandardSession.java:1673)
	at org.apache.catalina.session.StandardSession.writeObjectData(StandardSession.java:1079)
	at org.apache.catalina.session.StandardManager.doUnload(StandardManager.java:432)
	at org.apache.catalina.session.StandardManager.unload(StandardManager.java:353)
	at org.apache.catalina.session.StandardManager.stopInternal(StandardManager.java:518)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5622)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1564)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

@nbaars I believe you worked on this feature. Could you please check how we could serialize the session here ?

**Comment by nbaars** [comment]
Fixed, waiting for pul request

**Comment by nbaars** [comment]
Needs more testing

**Comment by nbaars** [comment]
Pull request is available. Tested in standalone Tomcat.
