### ISSUE TITLE
Error starting muliple instances of webgoat 8.1.0 on same server

### ISSUE THREAD

**Issue by secdevop** [WebGoat/WebGoat#1294]
I am trying to run multiple instances of webgoat 8.1.0 in a single instance of Windows Server 2019.

**Command** 
java -Dfile.encoding=UTF-8  -Dhsqldb.port=9003 -jar "C:\Users\xxxx\Documents\webgoat2\webgoat-server-8.1.0.jar" --server.port=8081 --server.address=localhost

**Console Error Message**
2022-07-15 05:58:12.915  INFO 4296 --- [           main] org.owasp.webgoat.StartWebGoat           : Starting StartWebGoat v8.1.0 on server with PID 4296 (C:\Users\xxxx\Documents\webgoat2\webgoat-server-8.1.0.jar started by infra2 in C:\Users\xxxx\Documents\webgoat2\jdk-15.0.2_windows-x64_bin\jdk-15.0.2\bin)
2022-07-15 05:58:12.923 DEBUG 4296 --- [           main] org.owasp.webgoat.StartWebGoat           : Running with Spring Boot v2.2.2.RELEASE, Spring v5.2.2.RELEASE
2022-07-15 05:58:12.923  INFO 4296 --- [           main] org.owasp.webgoat.StartWebGoat           : No active profile set, falling back to default profiles: default
2022-07-15 05:58:14.961  INFO 4296 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2022-07-15 05:58:15.148  INFO 4296 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 173ms. Found 2 JPA repository interfaces.
2022-07-15 05:58:15.882  INFO 4296 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-07-15 05:58:16.257  WARN 4296 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-07-15 05:58:16.320  INFO 4296 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2022-07-15 05:58:16.320  INFO 4296 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3266 ms
2022-07-15 05:58:16.601  INFO 4296 --- [           main] org.owasp.webgoat.HSQLDBDatabaseConfig   : Starting internal database on port 9003 ...
[Server@]: [Thread[main,5,main]]: checkRunning(false) entered
[Server@]: [Thread[main,5,main]]: checkRunning(false) exited
[Server@]: [Thread[main,5,main]]: setDatabaseName(0,webgoat)
[Server@]: [Thread[main,5,main]]: checkRunning(false) entered
[Server@]: [Thread[main,5,main]]: checkRunning(false) exited
[Server@]: [Thread[main,5,main]]: setDatabasePath(0,C:\Users\xxxx/.webgoat-8.1.0//data/webgoat)
[Server@]: [Thread[main,5,main]]: checkRunning(false) entered
[Server@]: [Thread[main,5,main]]: checkRunning(false) exited
[Server@]: [Thread[main,5,main]]: setDaemon(true)
[Server@]: [Thread[main,5,main]]: checkRunning(false) entered
[Server@]: [Thread[main,5,main]]: checkRunning(false) exited
[Server@]: [Thread[main,5,main]]: setAddress(localhost)
[Server@]: [Thread[main,5,main]]: setTrace(false)
[Server@]: Initiating startup sequence...
[Server@]: [Thread[HSQLDB Server @,5,main]]: run()/openServerSocket():
java.net.BindException: Cannot assign requested address: bind
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:550)
        at java.base/sun.nio.ch.Net.bind(Net.java:539)
        at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:396)
        at java.base/java.net.ServerSocket.<init>(ServerSocket.java:282)
        at org.hsqldb.server.HsqlSocketFactory.createServerSocket(Unknown Source)
        at org.hsqldb.server.Server.openServerSocket(Unknown Source)
        at org.hsqldb.server.Server.run(Unknown Source)
        at org.hsqldb.server.Server.access$000(Unknown Source)
        at org.hsqldb.server.Server$ServerThread.run(Unknown Source)
[Server@]: Initiating shutdown sequence...
Exception in thread "HSQLDB Server @" java.lang.NullPointerException: Cannot invoke "java.lang.ThreadGroup.activeCount()" because "this.serverConnectionThreadGroup" is null
        at org.hsqldb.server.Server.shutdown(Unknown Source)
        at org.hsqldb.server.Server.run(Unknown Source)
        at org.hsqldb.server.Server.access$000(Unknown Source)
        at org.hsqldb.server.Server$ServerThread.run(Unknown Source)

I am able to set new port for Database but unable to set the database path : setDatabasePath(0,C:\Users\xxxx/.webgoat-8.1.0//data/webgoat)

**Comment by zubcevic** [comment]
It was not really build for multiple instances on the same machine. You have to do a lot of overrides of specific settings. See https://github.com/WebGoat/WebGoat/blob/develop/src/main/resources/application-webgoat.properties for settings you can override. perhaps -Duser.home will be enough for you. But I guess installing it on a Kubernetes/openshift cluster is easier.
8.2+ is also easier since it is all in one jar.
See for some instructions for OpenShift: https://github.com/zubcevic/webgoat-helm
