### ISSUE TITLE
AccessControl: FileNotFoundException: class path resource [webgoat/templates/list_users.html] cannot be opened because it does not exist

### ISSUE THREAD

**Issue by w-wagner** [WebGoat/WebGoat#1388]
I hope that I do not look stupid as hell, but when I try to load the userlist, I get the exception below. I guess this file is referenced and should exist.
I am running the latest JAR standalone distribution webgoat-2023.3.jar 

2023-01-12 12:36:01.673 ERROR 97115 --- [  XNIO-1 task-3] io.undertow.request                      : UT005023: Exception handling request to /WebGoat/access-control/users

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "class path resource [webgoat/templates/list_users.html]")
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-5.3.21.jar!/:5.3.21]
...
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.21.jar!/:5.3.21]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.18.Final.jar!/:2.2.18.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.18.Final.jar!/:2.2.18.Final]
...
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) ~[jboss-threads-3.1.0.Final.jar!/:3.1.0.Final]
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282) ~[xnio-api-3.8.7.Final.jar!/:3.8.7.Final]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "class path resource [webgoat/templates/list_users.html]")
	at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:235) ~[thymeleaf-3.0.15.RELEASE.jar!/:3.0.15.RELEASE]
	at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parseStandalone(AbstractMarkupTemplateParser.java:100) ~[thymeleaf-3.0.15.RELEASE.jar!/:3.0.15.RELEASE]
....
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.21.jar!/:5.3.21]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.21.jar!/:5.3.21]
	... 96 common frames omitted
Caused by: java.io.FileNotFoundException: class path resource [webgoat/templates/list_users.html] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:199) ~[spring-core-5.3.21.jar!/:5.3.21]
	at org.thymeleaf.spring5.templateresource.SpringResourceTemplateResource.reader(SpringResourceTemplateResource.java:103) ~[thymeleaf-spring5-3.0.15.RELEASE.jar!/:3.0.15.RELEASE]
	at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:223) ~[thymeleaf-3.0.15.RELEASE.jar!/:3.0.15.RELEASE]
	... 107 common frames omitted

**Comment by aolle** [comment]
Try to send the request with the expected Content-type header. 

I am going ahead and close this issue.
Regards.
