### ISSUE TITLE
Injection Flaws: LAB: DB SQL Injection - stack trace

### ISSUE THREAD

**Issue by mayhew64** [WebGoat/WebGoat#182]
action=[Ljava.lang.String;@7fb1ea0c}
2016-01-30 12:58:31,209 DEBUG - HH Leaving Session_id: 5149C83A9757FF694C1F696CA8256577
java.sql.SQLException: Unknown JDBC escape sequence: { ? = call EMPLOYEE_LOGIN(?,?) }
    at org.hsqldb.jdbc.jdbcConnection.onStartEscapeSequence(Unknown Source)
    at org.hsqldb.jdbc.jdbcConnection.nativeSQL(Unknown Source)
    at org.hsqldb.jdbc.jdbcPreparedStatement.<init>(Unknown Source)
    at org.hsqldb.jdbc.jdbcCallableStatement.<init>(Unknown Source)
    at org.hsqldb.jdbc.jdbcConnection.prepareCall(Unknown Source)
    at org.owasp.webgoat.plugin.dbsqlinjection.Login.login(Login.java:130)
    at org.owasp.webgoat.plugin.dbsqlinjection.Login.handleRequest(Login.java:76)
    at org.owasp.webgoat.plugin.dbsqlinjection.DBSQLInjection.handleRequest(DBSQLInjection.java:183)
    at org.owasp.webgoat.HammerHead.makeScreen(HammerHead.java:300)
    at org.owasp.webgoat.HammerHead.doPost(HammerHead.java:148)
    at org.owasp.webgoat.HammerHead.doGet(HammerHead.java:104)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)

**Comment by span** [comment]
Hmm, did this ever work on WebGoat 6 using HSQLDB?

Looking at http://www.hsqldb.org/doc/1.8/src/org/hsqldb/jdbc/jdbcCallableStatement.html it seems that the syntax should be `{?= call...}`.

Look at the docs for [org.hsqldb.jdbc.jdbcConnection.nativeSQL](http://hsqldb.org/doc/src/org/hsqldb/jdbc/JDBCConnection.html) they claim that HSQLDB is very sensitive to the whitespace in the statement from 1.7.2:

>  But to avoid a great deal of complexity, certain forms of input whitespace are currently not recognised. For instance, the driver handles "{?= call ...}" but not "{ ?= call ...} or "{? = call ...}" 

But it also says:

> It is intended to implement a less strict handling of whitespace and proper processing of SQL comments at some point in the near future.

Anyway, I had a look at it and failed miserably. When using the recommended syntax it failed in the init methods of the prepared/callable statement classes.

```
String call = "{?= call EMPLOYEE_LOGIN(?,?)}";
```

```
java.sql.SQLException: Unexpected token: EMPLOYEE_LOGIN in statement [    call EMPLOYEE_LOGIN(?,?) ]
	at org.hsqldb.jdbc.Util.throwError(Unknown Source)
	at org.hsqldb.jdbc.jdbcPreparedStatement.<init>(Unknown Source)
	at org.hsqldb.jdbc.jdbcCallableStatement.<init>(Unknown Source)
	at org.hsqldb.jdbc.jdbcConnection.prepareCall(Unknown Source)
	at org.owasp.webgoat.plugin.dbsqlinjection.Login.login(Login.java:130)
```

**Comment by span** [comment]
Updating to HSQLDB 2.3.3 by changing the version number and updating the groupid to `org.hsqldb` so that it can be fetched from the central maven repo fixes the stack trace. It still gives an error though.

> * Error logging in: user lacks privilege or object not found: EMPLOYEE_LOGIN

So either the db is not initiated with the function or something else could be amiss. I'm having some issues working out how the different kinds of persistence works so it is a bit slow.

**Comment by span** [comment]
Stabbed some more on this using the DatabaseManagerSwing util and I could not find any functions added to the database. I tried adding the functions from both `webgoat_oracle.sql` and `webgoat_sqlserver.sql` but they both fail with syntax errors for HSQLDB.

**Comment by span** [comment]
Sorry for nagging on this but did this ever work on WebGoat 6 using HSQLDB? If so, does anyone remember how the functions/statements were added?

**Comment by mayhew64** [comment]
Can't say definitely it worked in WebGoat 6, but it did work in 5.4

**Comment by nbaars** [comment]
The lesson used to work with a stored procedure.  The Login_i.java gives one for Oracle and SqlServer there seems to be no equivalent for HSQLDB

**Comment by nbaars** [comment]
Closing, since the release of version 8.0 we no longer actively support version 7.1.
