### ISSUE TITLE
WSDL link in SOAP Request Lesson crashing with AXIS error

### ISSUE THREAD

**Issue by samstep** [WebGoat/WebGoat#221]
WebGoat 7.0.1 error:

Steps to re-produce: 

1. Go to Web Services / Create a SOAP Request
2. Click on WebGoat WSDL file:

/WebGoat/services/SoapRequest?WSDL

**AXIS error**

Sorry, something seems to have gone wrong... here are the details:

**Fault - ; nested exception is: 
	org.apache.axis.ConfigurationException: Could not find class for the service named: org.owasp.webgoat.lessons.SoapRequest**
Hint: you may need to copy your class files/tree into the right location (which depends on the servlet system you are using).; nested exception is: 
	java.lang.ClassNotFoundException: org.owasp.webgoat.lessons.SoapRequest

--

`
	java.lang.ClassNotFoundException: org.owasp.webgoat.lessons.SoapRequest
	at org.apache.axis.providers.java.JavaProvider.getServiceClass(JavaProvider.java:432)
	at org.apache.axis.providers.java.JavaProvider.initServiceDesc(JavaProvider.java:461)
	at org.apache.axis.handlers.soap.SOAPService.getInitializedServiceDesc(SOAPService.java:286)
	at org.apache.axis.deployment.wsdd.WSDDService.makeNewInstance(WSDDService.java:500)
	at org.apache.axis.deployment.wsdd.WSDDDeployableItem.getNewInstance(WSDDDeployableItem.java:274)
	at org.apache.axis.deployment.wsdd.WSDDDeployableItem.getInstance(WSDDDeployableItem.java:260)
	at org.apache.axis.deployment.wsdd.WSDDDeployment.getService(WSDDDeployment.java:427)
	at org.apache.axis.configuration.FileProvider.getService(FileProvider.java:231)
	at org.apache.axis.AxisEngine.getService(AxisEngine.java:311)
	at org.apache.axis.MessageContext.setTargetService(MessageContext.java:756)
	at org.apache.axis.handlers.http.URLMapper.invoke(URLMapper.java:50)
	at org.apache.axis.handlers.http.URLMapper.generateWSDL(URLMapper.java:58)
	at org.apache.axis.strategies.WSDLGenStrategy.visit(WSDLGenStrategy.java:33)
	at org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
	at org.apache.axis.SimpleChain.generateWSDL(SimpleChain.java:104)
	at org.apache.axis.server.AxisServer.generateWSDL(AxisServer.java:446)
	at org.apache.axis.transport.http.QSWSDLHandler.invoke(QSWSDLHandler.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.axis.transport.http.AxisServlet.processQuery(AxisServlet.java:1226)
	at org.apache.axis.transport.http.AxisServlet.doGet(AxisServlet.java:249)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at org.apache.axis.transport.http.AxisServletBase.service(AxisServletBase.java:327)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)`
....

**Comment by nbaars** [comment]
Fixed the classname in the wsdd configuration file, WSDL is working again

@samstep are you able to test the lessons with the develop build of WebGoat? Thanks in advance.

**Comment by nbaars** [comment]
Closing seems to work

**Comment by victorfsf** [comment]
How can we fix this problem?
