### ISSUE TITLE
Images in AsciiDoc

### ISSUE THREAD

**Issue by misfir3** [WebGoat/WebGoat#293]
Currently adding images in *.adoc (e.g.) files creates an error ...

In *.html file
`<div class="adoc-content" th:replace="doc:HttpBasics_ProxyIntro2.adoc"></div>`

in *.adoc file:
`image::images/zap-local-proxy.png[caption="local proxy config for zap"]`

Error Stack Trace:
`org.xml.sax.SAXParseException: The element type "img" must be terminated by the matching end-tag "</img>".
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source) [xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source) [xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) [xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) [xercesImpl-2.11.0.jar:na]
...
016-12-07 12:23:49.822 ERROR 43466 --- [nio-8080-exec-5] org.thymeleaf.TemplateEngine             : [THYMELEAF][http-nio-8080-exec-5] Exception processing template "lesson_content": Exception parsing document: template="doc:HttpBasics_ProxyIntro2.adoc", line 25 - column 3 (lesson:HttpBasics:102)
2016-12-07 12:23:49.824 ERROR 43466 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/WebGoat] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: Exception parsing document: template="doc:HttpBasics_ProxyIntro2.adoc", line 25 - column 3 (lesson:HttpBasics:102)] with root cause

org.xml.sax.SAXParseException: The element type "img" must be terminated by the matching end-tag "</img>".
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.11.0.jar:na]`

**Comment by misfir3** [comment]
Short version, we need to find if there's a way to get asciidoc to output images with closing tags so that thymeleaf is happy with the output.

**Comment by misfir3** [comment]
According to this (below), we should be able to set the backend to xhtml5 to resolve it ... will test later:

https://github.com/asciidoctor/asciidoctorj/issues/538
