### ISSUE TITLE
WebGoat lessons do not load

### ISSUE THREAD

**Issue by mayhew64** [WebGoat/WebGoat#32]
Following the README instructions from a clean system.  The following error occurs and the lessons do not load.  WebGoat will start and the login screen appears, after login there is no content.

INFO: WebGoat is starting
Aug 21, 2015 8:45:28 AM org.apache.catalina.session.StandardManager doLoad
SEVERE: IOException while loading persisted sessions: java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: org.owasp.webgoat.util.LabelManagerImpl
java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: org.owasp.webgoat.util.LabelManagerImpl
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1355)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.apache.catalina.session.StandardSession.readObject(StandardSession.java:1595)
	at org.apache.catalina.session.StandardSession.readObjectData(StandardSession.java:1060)
	at org.apache.catalina.session.StandardManager.doLoad(StandardManager.java:284)
	at org.apache.catalina.session.StandardManager.load(StandardManager.java:204)
	at org.apache.catalina.session.StandardManager.startInternal(StandardManager.java:491)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5300)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.NotSerializableException: org.owasp.webgoat.util.LabelManagerImpl
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.catalina.session.StandardSession.writeObject(StandardSession.java:1671)
	at org.apache.catalina.session.StandardSession.writeObjectData(StandardSession.java:1077)
	at org.apache.catalina.session.StandardManager.doUnload(StandardManager.java:432)
	at org.apache.catalina.session.StandardManager.unload(StandardManager.java:353)
	at org.apache.catalina.session.StandardManager.stopInternal(StandardManager.java:518)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5479)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1564)
	... 4 more

Aug 21, 2015 8:45:28 AM org.apache.catalina.session.StandardManager startInternal
SEVERE: Exception loading sessions from persistent storage
java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: org.owasp.webgoat.util.LabelManagerImpl
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1355)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.apache.catalina.session.StandardSession.readObject(StandardSession.java:1595)
	at org.apache.catalina.session.StandardSession.readObjectData(StandardSession.java:1060)
	at org.apache.catalina.session.StandardManager.doLoad(StandardManager.java:284)
	at org.apache.catalina.session.StandardManager.load(StandardManager.java:204)
	at org.apache.catalina.session.StandardManager.startInternal(StandardManager.java:491)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5300)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.NotSerializableException: org.owasp.webgoat.util.LabelManagerImpl
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.catalina.session.StandardSession.writeObject(StandardSession.java:1671)
	at org.apache.catalina.session.StandardSession.writeObjectData(StandardSession.java:1077)
	at org.apache.catalina.session.StandardManager.doUnload(StandardManager.java:432)
	at org.apache.catalina.session.StandardManager.unload(StandardManager.java:353)
	at org.apache.catalina.session.StandardManager.stopInternal(StandardManager.java:518)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5479)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1564)
	... 4 more

Aug 21, 2015 8:45:28 AM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring FrameworkServlet 'mvc-dispatcher'
[INFO] FrameworkServlet 'mvc-dispatcher': initialization started

**Comment by nbaars** [comment]
This exception is, I think, also present in the legacy project. This exception has always been present during the startup. I don't think the loading fails due to this exception. Debugged this part but all the plugins are correctly loaded.

I debugged with Firefox and the json request:

```
http://localhost:8080/WebGoat/service/lessonmenu.mvc
```

returns all the lessons however does not display them. 
If I specify in the class Course to only load 10 lessons it does work, the same json response is returned with only 10 elements.

So maybe this issue is UI related? Could also be that the first lessons which opens as default has an issue?
@misfir3 can you take a quick look what happens when we load all the lessons? Maybe you immediately see what's going on?

Thanks

**Comment by misfir3** [comment]
I noted an issue last night that I errantly introduced recently where only one lesson would initially load, then subsequent lessons would not (had changed to listenToOnce where it should have remained listenTo in the LessonController).  Let me know if this is still happening after pulling my merge from yesterday.

**Comment by dougmorato** [comment]
And I thought it was just my machine... I tried late night yesterday to go check the lessons but I get a black page after login.

I tried using the _mvn tomcat7-run-war_ and using the _executable-jar_ options, but no luck.

__Question:__ Previous instructions said to copy the lessons/target/*.jar to WebGoat/webgoat-container/target/webgoat-container-6.1.0/plugin_lessons/ . 
The web-container/target directory does not exists when we do _mvn clean compile_ .
I am assuming we copy should all the *.jar to WebGoat/webgoat-container/src/main/webapp/plugins, so when we call _mvn package_, the .war and exec.jar would then include the lessons. Is this correct?

__If correct, I will update the README to reflect this__

**Comment by dougmorato** [comment]
@misfir3 I forgot to mention that I tried this yesterday at 11PM, after you PR was merged

**Comment by misfir3** [comment]
@dougmorato Do you have firebug in your env?
1) Do you get the menu, but no lessons (as Bruce noted)
2) If yes to 1, do do you see 1 or ~ 6 calls in the FireBug console after clicking on a lesson?
3) Do you see any errors in the console?

As to ...
> I am assuming we copy should all the *.jar to WebGoat/webgoat-container/src/main/webapp/plugins, so when we call mvn package, the .war and exec.jar would then include the lessons. Is this correct?"

I believe that is correct. I have to copy the files over and restart tomcat to get them in the menu or be able to view them.

**Comment by dougmorato** [comment]
So, I have no menu and no lessons, as can be seen in attached screenshot:
<img width="801" alt="nomennunolessons" src="https://cloud.githubusercontent.com/assets/9654/9414334/977db6d2-4805-11e5-8434-4b0d01bf65bc.png">

Going to [http://localhost:8080/WebGoat/service/lessonmenu.mvc](http://localhost:8080/WebGoat/service/lessonmenu.mvc) , I do see the list of lessons in JSON format.

<img width="597" alt="lessonmenu_mvc" src="https://cloud.githubusercontent.com/assets/9654/9414344/ac56a258-4805-11e5-942d-16841805b6ca.png">

**Comment by nbaars** [comment]
> I am assuming we copy should all the *.jar to WebGoat/webgoat-container/src/main/webapp/plugins,  when we call mvn package, the .war and exec.jar would then include the lessons. Is this correct?"

Yes that's correct. There is no reload policy in place yet but I think we can add an endpoint which reloads the lessons.

The packages was solved by the webgoat-release project. This project is now disabled the idea was to build the container build the lessons copy the lessons and create the war. This can easily be scripted in Travis CI so I think we can remove this project.

**Comment by nbaars** [comment]
@misfir3 I updated everything and the lessons do not load. I see the same json as @dougmorato. In Firebug there is one XHR call.

**Comment by misfir3** [comment]
OK, I'll make sure I'm all updated and take another look later today when I can get some quality time with my laptop. One XHR (which is to the attak.jsp?menu=x&screen=y I assume) means something happened to the onContentLoaded callback.  Maybe I over-cleaned something, although I was checking those incrementally. <sigh/>

**Comment by misfir3** [comment]
PR is in. Once someone can confirm, I will close this.
