### ISSUE TITLE
No message found under code 'http-basics.reversed' for locale 'en_US'.

### ISSUE THREAD

**Issue by 5teven-tian** [WebGoat/WebGoat#339]
Version number is 8.0-SNAPSHOT,

Reproduce step:

1.go to link http://localhost:8080/WebGoat/start.mvc#lesson/HttpBasics.lesson/1
2.input name
3.press "Go" button, then this exception occurred.

Following is its exception log:
=============================================

org.springframework.context.NoSuchMessageException: No message found under code 'http-basics.reversed' for locale 'en_US'.
	at org.springframework.context.support.AbstractMessageSource.getMessage(AbstractMessageSource.java:159) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.owasp.webgoat.i18n.PluginMessages.getMessage(PluginMessages.java:58) ~[classes/:na]

**Comment by nbaars** [comment]
This error has been fixed in the current development branch, also available on Docker Hub.
