### ISSUE TITLE
WebGoat 8.0 Docker container creation fails when behind proxy

### ISSUE THREAD

**Issue by l50** [WebGoat/WebGoat#380]
```
java.io.IOException: Could not open inputStream for http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.2.2.tgz
	at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:131) ~[de.flapdoodle.embed.process-1.50.2.jar!/:na]
	at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java:69) ~[de.flapdoodle.embed.process-1.50.2.jar!/:na]
	at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:66) ~[de.flapdoodle.embed.process-1.50.2.jar!/:na]
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.checkDistribution(ExtractedArtifactStore.java:60) ~[de.flapdoodle.embed.process-1.50.2.jar!/:na]
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:56) [de.flapdoodle.embed.process-1.50.2.jar!/:na]
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:49) [de.flapdoodle.embed.process-1.50.2.jar!/:na]
	at org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration.embeddedMongoServer(EmbeddedMongoAutoConfiguration.java:114) [spring-boot-autoconfigure-1.5.3.RELEASE.jar!/:1.5.3.RELEASE]
	at org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration$$EnhancerBySpringCGLIB$$bef92408.CGLIB$embeddedMongoServer$1(<generated>) [spring-boot-autoconfigure-1.5.3.RELEASE.jar!/:1.5.3.RELEASE]
	at org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration$$EnhancerBySpringCGLIB$$bef92408$$FastClassBySpringCGLIB$$ee71765e.invoke(<generated>) [spring-boot-autoconfigure-1.5.3.RELEASE.jar!/:1.5.3.RELEASE]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) [spring-core-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) [spring-context-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
...
```

**Comment by misfir3** [comment]
I encountered this also a little while back, when I was offline and trying to create a new container locally.

**Comment by l50** [comment]
Sure, if you're offline then it won't be able to pull the tgz file. In my case we're online but there is a proxy involved.

**Comment by misfir3** [comment]
If the proxy is blocking/filtering that off ... same net result, no? Can you download that artifact directly from a browser behind the same proxy?

**Comment by nbaars** [comment]
Correct, it uses the internal MongoDB which needs to download it. Think we can fix the Docker part by just downloading it upfront and specify the directory so the download does not happen again

**Comment by l50** [comment]
I can wget it from within the docker container:
```
docker start <container name> && docker exec -it <container name> /bin/bash
cd /tmp
wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.2.2.tgz
mongodb-linux-x86_64-3.2.2.tgz.1               5%[====> *cut out, but you get the idea*
```

**Comment by l50** [comment]
@nbaars that seems reasonable to me. Only problem then will be ensuring that if users need to use a new version, that it is kept up-to-date in subsequent releases.

**Comment by nbaars** [comment]
If you put in /home/webgoat/.embedmongo/linux it should be able to find it

**Comment by l50** [comment]
@nbaars The tgz file?

**Comment by nbaars** [comment]
Yes

**Comment by nbaars** [comment]
Adjusted the Docker file locally and disconnected my VM seems to work. Docker container did extract the *.gz file

**Comment by l50** [comment]
@nbaars Something like this?
```
# On docker engine host:
wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.2.2.tgz
# In Dockerfile:
...
COPY webgoat-server-8.0-SNAPSHOT.jar /home/webgoat/webgoat.jar
# introduce change here:
COPY ./mongodb-linux-x86_64-3.2.2.tgz /home/webgoat/.embedmongo/linux/mongodb-linux-x86_64-3.2.2.tgz
...
```

**Comment by nbaars** [comment]
That would work as well incorporated the download in the Docker file, during our build it will be able to download it.

**Comment by misfir3** [comment]
cc @dougmorato - since he volunteered on looking into an automated docker build

**Comment by l50** [comment]
Awesome, thanks for the quick turnaround!
