### ISSUE TITLE
PluginLoader Error / List out of bounds crash

### ISSUE THREAD

**Issue by Mergis** [WebGoat/WebGoat#397]
**I'm getting 3 errors on deployment:**

_2017-10-23 00:43:15.766 ERROR 2567 --- [           main] org.owasp.webgoat.plugins.PluginsLoader  : No lessons found if you downloaded an official release of WebGoat please take the time to
2017-10-23 00:43:15.766 ERROR 2567 --- [           main] org.owasp.webgoat.plugins.PluginsLoader  : create a new issue at https://github.com/WebGoat/WebGoat/issues/new
2017-10-23 00:43:15.766 ERROR 2567 --- [           main] org.owasp.webgoat.plugins.PluginsLoader  : For developers run 'mvn package' first from the root directory._

**The server starts up though as soon as you create a user and log in then it throws this:**

_2017-10-23 00:43:22.271  INFO 2567 --- [           main] org.owasp.webgoat.WebGoat                : Started WebGoat in 12.28 seconds (JVM running for 17.803)
2017-10-23 00:44:10.575  INFO 2567 --- [nio-8080-exec-1] o.a.c.c.C.[.[localhost].[/WebGoat]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2017-10-23 00:44:10.657 DEBUG 2567 --- [nio-8080-exec-1] org.owasp.webgoat.i18n.Messages          : Loading properties [messages.properties]
2017-10-23 00:44:10.659 DEBUG 2567 --- [nio-8080-exec-1] org.owasp.webgoat.i18n.Messages          : No properties file found for [classpath:i18n/messages_en_NZ] - neither plain properties nor XML
2017-10-23 00:44:10.660 DEBUG 2567 --- [nio-8080-exec-1] org.owasp.webgoat.i18n.Messages          : No properties file found for [classpath:i18n/messages_en] - neither plain properties nor XML
2017-10-23 00:44:10.660 DEBUG 2567 --- [nio-8080-exec-1] org.owasp.webgoat.i18n.Messages          : No properties file found for [classpath:i18n/messages_en_US] - neither plain properties nor XML
2017-10-23 00:44:40.288  INFO 2567 --- [nio-8080-exec-9] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:10}] to localhost:27017
2017-10-23 00:45:12.495 ERROR 2567 --- [nio-8080-exec-9] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] threw exception_

**Following the stack trace i find:**

_2017-10-23 00:45:12.502 ERROR 2567 --- [nio-8080-exec-9] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/WebGoat] threw exception [Request processing failed; nested exception is java.lang.IndexOutOfBoundsException: Index: 0, Size: 0] with root cause

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[na:1.8.0_131]
	at java.util.ArrayList.get(ArrayList.java:429) ~[na:1.8.0_131]
	at org.owasp.webgoat.session.Course.getFirstLesson(Course.java:66) ~[classes/:na]
	at org.owasp.webgoat.HammerHead.attack(HammerHead.java:59) ~[classes/:na]_

**Comment by nbaars** [comment]
@Mergis which version did you try?

**Comment by Mergis** [comment]
@nbaars git cloned from here 3 days ago

**Comment by Mergis** [comment]
Looks like instructions attached to main page have changed since here is outcome from running fist command in those:

<b>user@ubuntu:~$ sudo git clone git@github.com:WebGoat/WebGoat.git

Cloning into 'WebGoat'...
Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.</b>

so have used <b>"sudo git clone https://github.com/WebGoat/WebGoat.git"</b>
after building it doesn't report the errors as it did before but it cant be reached by browser at all now

**Comment by Mergis** [comment]
Sorry ran out of time yesterday to actually look into what was going on.
Can reach <ip-address>:8081/WebWolf but not <ip-address>:8080/WebGoat (dont even get the fall back message), <ip-address>:8081/WebGoat produces fallback error message.

**Comment by nbaars** [comment]
@Mergis we updated the readme, it was refering to the wrong command, should be:

```
mvn clean package
mvn -pl webgoat-server spring-boot:run
```
