### ISSUE TITLE
Connecting to mongo giving error

### ISSUE THREAD

**Issue by shashwat001** [WebGoat/WebGoat#415]
Getting error when trying following command
`mvn -pl webwolf spring-boot:run`

The error log is
```
2017-12-27 22:53:47.871  INFO 9539 --- [  restartedMain] org.owasp.webwolf.WebWolf                : Starting WebWolf on myhostname with PID 9539 (/home/shashwat/Documents/WebGoat/webwolf/target/classes started by shashwat in /home/shashwat/Documents/WebGoat)
2017-12-27 22:53:47.872 DEBUG 9539 --- [  restartedMain] org.owasp.webwolf.WebWolf                : Running with Spring Boot v1.5.5.RELEASE, Spring v4.3.10.RELEASE
2017-12-27 22:53:47.873  INFO 9539 --- [  restartedMain] org.owasp.webwolf.WebWolf                : No active profile set, falling back to default profiles: default
2017-12-27 22:53:48.082  INFO 9539 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@b24726c: startup date [Wed Dec 27 22:53:48 IST 2017]; root of context hierarchy
2017-12-27 22:53:49.556  INFO 9539 --- [  restartedMain] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8081 (http)
2017-12-27 22:53:49.569  INFO 9539 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2017-12-27 22:53:49.570  INFO 9539 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.16
2017-12-27 22:53:49.653  INFO 9539 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2017-12-27 22:53:49.653  INFO 9539 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1575 ms
2017-12-27 22:53:49.993  INFO 9539 --- [ost-startStop-1] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=MULTIPLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2017-12-27 22:53:49.994  INFO 9539 --- [ost-startStop-1] org.mongodb.driver.cluster               : Adding discovered server localhost:27017 to client view of cluster
2017-12-27 22:53:50.036  INFO 9539 --- [localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.SocketStream.open(SocketStream.java:63) ~[mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:113) ~[mongodb-driver-core-3.4.2.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_111]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_111]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_111]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_111]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_111]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_111]
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:57) ~[mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongodb-driver-core-3.4.2.jar:na]
	... 3 common frames omitted

2017-12-27 22:53:50.225  INFO 9539 --- [ost-startStop-1] org.mongodb.driver.cluster               : No server chosen by WritableServerSelector from cluster description ClusterDescription{type=UNKNOWN, connectionMode=MULTIPLE, serverDescriptions=[ServerDescription{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]}. Waiting for 30000 ms before timing out
```

Please suggest how to get rid of this. I could not find anything related on web.
I dont have mongo installed as it was not mentioned in prerequisites.

**Comment by nbaars** [comment]
Hi @shashwat001 

WebWolf can only run if you have started WebGoat before. WebWolf reuses the user management of WebGoat (for now). Can you first start WebGoat and then run WebWolf?

Thanks,
--Nanne

**Comment by nbaars** [comment]
@shashwat001 see release https://github.com/WebGoat/WebGoat/releases/tag/v8.0.0.M6 we removed the MongoDB dependency, more users reported the same issue.

Thanks for reporting the issue
