### ISSUE TITLE
Version: docker 8.0.0.M9 Multiple users can't finalize the same lesson

### ISSUE THREAD

**Issue by hexfred** [WebGoat/WebGoat#432]
I've registered two user accounts connecting on the same webgoat/webgoat-8.0 docker container.
If one user validates an exercise, the other one can no more validate it.
I get an SQL exception in the logs:

> 2018-01-27 14:17:01.528  WARN 5 --- [nio-8080-exec-7] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: -104, SQLState: 23505
2018-01-27 14:17:01.528 ERROR 5 --- [nio-8080-exec-7] o.h.engine.jdbc.spi.SqlExceptionHelper   : integrity constraint violation: unique constraint or index violation; UK_R9V8LMV8SEFH9EFVYW916JOLS table: USER_TRACKER_LESSON_TRACKERS
2018-01-27 14:17:01.530  INFO 5 --- [nio-8080-exec-7] o.h.e.j.b.internal.AbstractBatchImpl     : HHH000010: On release of batch it still contained JDBC statements
2018-01-27 14:17:01.559  WARN 5 --- [nio-8080-exec-7] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: -104, SQLState: 23505
2018-01-27 14:17:01.559 ERROR 5 --- [nio-8080-exec-7] o.h.engine.jdbc.spi.SqlExceptionHelper   : integrity constraint violation: unique constraint or index violation; UK_R9V8LMV8SEFH9EFVYW916JOLS table: USER_TRACKER_LESSON_TRACKERS
2018-01-27 14:17:01.559  INFO 5 --- [nio-8080-exec-7] o.h.e.j.b.internal.AbstractBatchImpl     : HHH000010: On release of batch it still contained JDBC statements
2018-01-27 14:17:01.566 ERROR 5 --- [nio-8080-exec-7] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/WebGoat] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [UK_R9V8LMV8SEFH9EFVYW916JOLS]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement] with root cause org.hsqldb.HsqlException: integrity constraint violation: unique constraint or index violation; UK_R9V8LMV8SEFH9EFVYW916JOLS table: USER_TRACKER_LESSON_TRACKERS
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.3.2.jar!/:2.3.2]
	at org.hsqldb.Constraint.getException(Unknown Source) ~[hsqldb-2.3.2.jar!/:2.3.2]
	at org.hsqldb.index.IndexAVLMemory.insert(Unknown Source) ~[hsqldb-2.3.2.jar!/:2.3.2]
	at org.hsqldb.persist.RowStoreAVL.indexRow(Unknown Source) ~[hsqldb-2.3.2.jar!/:2.3.2]
	at org.hsqldb.TransactionManager2PL.addInsertAction(Unknown Source) ~[hsqldb-2.3.2.jar!/:2.3.2]
	at org.hsqldb.Session.addInsertAction(Unknown Source) ~[hsqldb-2.3.2.jar!/:2.3.2]
	at org.hsqldb.Table.insertSingleRow(Unknown Source) ~[hsqldb-2.3.2.jar!/:2.3.2]
	at org.hsqldb.StatementDML.insertSingleRow(Unknown Source) ~[hsqldb-2.3.2.jar!/:2.3.2]
	at org.hsqldb.StatementInsert.getResult(Unknown Source) ~[hsqldb-2.3.2.jar!/:2.3.2]
	at org.hsqldb.StatementDMQL.execute(Unknown Source) ~[hsqldb-2.3.2.jar!/:2.3.2]
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source) ~[hsqldb-2.3.2.jar!/:2.3.2]
	at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.3.2.jar!/:2.3.2]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.3.2.jar!/:2.3.2]
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source) ~[hsqldb-2.3.2.jar!/:2.3.2]
	at sun.reflect.GeneratedMethodAccessor143.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc-8.5.23.jar!/:na]
	at com.sun.proxy.$Proxy118.executeUpdate(Unknown Source) ~[na:na]
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:204) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:45) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.persister.collection.AbstractCollectionPersister.insertRows(AbstractCollectionPersister.java:1554) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.action.internal.CollectionUpdateAction.execute(CollectionUpdateAction.java:85) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:582) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:456) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1282) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:465) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:2963) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2339) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:485) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:147) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$100(JdbcResourceLocalTransactionCoordinatorImpl.java:38) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:231) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:65) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.jpa.internal.TransactionImpl.commit(TransactionImpl.java:61) ~[hibernate-entitymanager-5.0.12.Final.jar!/:5.0.12.Final]
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:517) ~[spring-orm-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761) ~[spring-tx-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730) ~[spring-tx-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:518) ~[spring-tx-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:292) ~[spring-tx-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) ~[spring-tx-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:133) ~[spring-data-jpa-1.11.9.RELEASE.jar!/:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57) ~[spring-data-commons-1.13.9.RELEASE.jar!/:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at com.sun.proxy.$Proxy97.save(Unknown Source) ~[na:na]
	at org.owasp.webgoat.assignments.AssignmentEndpoint.trackProgress(AssignmentEndpoint.java:67) ~[webgoat-container-8.0.0.M9.jar!/:8.0.0.M9]
	at org.owasp.webgoat.plugin.introduction.SqlInjectionLesson5a.injectableQuery(SqlInjectionLesson5a.java:91) ~[sql-injection-8.0.0.M9.jar!/:8.0.0.M9]
	at org.owasp.webgoat.plugin.introduction.SqlInjectionLesson5a.completed(SqlInjectionLesson5a.java:56) ~[sql-injection-8.0.0.M9.jar!/:8.0.0.M9]`

Thanks

**Comment by nbaars** [comment]
Correct, this issue has been fixed in v8.0.0.M10
@hexfred  can you try again with the new version?

Thanks for reporting this issue

**Comment by hexfred** [comment]
Hi @nbaars ,
I'm probably doing something wrong. 
The latest docker image (8.0.0.M10) starts properly but is not reachable out of container.
docker run -p 80:8080 -it webgoat/webgoat-8.0 /home/webgoat/start.sh

From my MacBook :
curl -v http://$(docker-machine ip training2):80/WebGoat
*   Trying 192.168.99.100...
* TCP_NODELAY set
* Connection failed
* connect to 192.168.99.100 port 80 failed: Connection refused
* Failed to connect to 192.168.99.100 port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 192.168.99.100 port 80: Connection refused

From the container:
curl -v http://127.0.0.1:8080/WebGoat
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /WebGoat HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 302
< Location: http://127.0.0.1:8080/WebGoat/
< Transfer-Encoding: chunked
< Date: Mon, 29 Jan 2018 21:32:13 GMT
<
* Curl_http_done: called premature == 0
* Connection #0 to host 127.0.0.1 left intact

docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                  NAMES
b16a2d5b606f        webgoat/webgoat-8.0   "/home/webgoat/start…"   9 minutes ago       Up 9 minutes        0.0.0.0:80->8080/tcp   relaxed_sinoussi

**Comment by hexfred** [comment]
Hi @nbaars,

I've installed the net-tools package into the conatiner and checked the TCP port binding.
`netstat -atpn`

> Active Internet connections (servers and established)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
> tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      -

The Tomcat server is now bound to the loopback interface only.

**Comment by nbaars** [comment]
@hexfred correct, made the change you proposed to the Docker file in the other issue. This release is available as v8.0.0.M12

**Comment by hexfred** [comment]
Hi @nbaars,
Multiple users can now complete the same exercise.
Thanks a lot to have fixed this issue.
