### ISSUE TITLE
Clicking on 'LAB: Role Based Access Control' produces 'Invalid Session' in UI

### ISSUE THREAD

**Issue by misfir3** [WebGoat/WebGoat#44]
The stack trace is ...
2015-08-23 00:33:28,276 DEBUG - HH Entering Session_id: 10593521B908AFB0D490A02640CA96DB
2015-08-23 00:33:28,276 ERROR - Error handling request
java.lang.NumberFormatException: For input string: "null"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.owasp.webgoat.session.ParameterParser.getIntParameter(ParameterParser.java:377)
	at org.owasp.webgoat.session.WebSession.update(WebSession.java:845)
	at org.owasp.webgoat.HammerHead.updateSession(HammerHead.java:403)
	at org.owasp.webgoat.HammerHead.doPost(HammerHead.java:132)
	at org.owasp.webgoat.HammerHead.doGet(HammerHead.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
...

When I change the URL from:
http://localhost:8080/WebGoat/start.mvc#attack/152/200
to
http://localhost:8080/WebGoat/start.mvc#attack/152/200/0
... it appears to work (since support was added for the stage param), but has 'Stage 2' above in the view.

@nbaars or @WebGoat you may be able to decipher a little better than me what's going on.

**Comment by nbaars** [comment]
To reproduce you need to click stage 4 and then Lab Role based access control again

**Comment by nbaars** [comment]
Fixed the issue was that the stage parameter is posted as "null" like: `String s = "null"`
This can never be formatted into an integer which made the page crash. Added an extra check when we are dealing with a `RandomLessonAdapter` to reset the stage.

The main entry point of the lab now displays the text of the first stage in the lab, this makes more sense because previously if you clicked the main entry point only a Goathill financial part was shown (no text).
