### ISSUE TITLE
Issue Installing Webgoat

### ISSUE THREAD

**Issue by sharmaaddy** [WebGoat/WebGoat#497]
Hello Everyone,

I am new to webgoat and I am having some issues installing it on my ubuntu/kali machine. 
I did a simple download of the jar file from the git release page and executed the command 

java -jar webgoat-server-8.0.0.M21.jar 
but apparently the error I have is same on both machines: 

java -jar webgoat-server-8.0.0.M21.jar 

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v1.5.12.RELEASE)

2018-06-30 17:16:36.188  INFO 3733 --- [           main] org.owasp.webgoat.StartWebGoat           : Starting StartWebGoat v8.0.0.M21 on kali with PID 3733 (/root/webgoat/webgoat-server-8.0.0.M21.jar started by root in /root/webgoat)
2018-06-30 17:16:36.191 DEBUG 3733 --- [           main] org.owasp.webgoat.StartWebGoat           : Running with Spring Boot v1.5.12.RELEASE, Spring v4.3.16.RELEASE
2018-06-30 17:16:36.191  INFO 3733 --- [           main] org.owasp.webgoat.StartWebGoat           : No active profile set, falling back to default profiles: default
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (jar:file:/root/webgoat/webgoat-server-8.0.0.M21.jar!/BOOT-INF/lib/groovy-2.4.15.jar!/) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2018-06-30 17:16:36.545  INFO 3733 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@4f83df68: startup date [Sat Jun 30 17:16:36 CEST 2018]; root of context hierarchy
2018-06-30 17:16:38.438  INFO 3733 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$b4f5109d] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-06-30 17:16:39.075  INFO 3733 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2018-06-30 17:16:39.108  INFO 3733 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2018-06-30 17:16:39.108  INFO 3733 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.29
2018-06-30 17:16:39.264  INFO 3733 --- [ost-startStop-1] o.a.c.c.C.[.[localhost].[/WebGoat]       : Initializing Spring embedded WebApplicationContext
2018-06-30 17:16:39.264  INFO 3733 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2737 ms
2018-06-30 17:16:39.521  INFO 3733 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'metricsFilter' to: [/*]
2018-06-30 17:16:39.522  INFO 3733 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2018-06-30 17:16:39.522  INFO 3733 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2018-06-30 17:16:39.522  INFO 3733 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2018-06-30 17:16:39.523  INFO 3733 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2018-06-30 17:16:39.524  INFO 3733 --- [ost-startStop-1] .s.DelegatingFilterProxyRegistrationBean : Mapping filter: 'springSecurityFilterChain' to: [/*]
2018-06-30 17:16:39.524  INFO 3733 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'webRequestLoggingFilter' to: [/*]
2018-06-30 17:16:39.524  INFO 3733 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'applicationContextIdFilter' to: [/*]
2018-06-30 17:16:39.525  INFO 3733 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
[Server@3044e9c7]: [Thread[main,5,main]]: checkRunning(false) entered
[Server@3044e9c7]: [Thread[main,5,main]]: checkRunning(false) exited
[Server@3044e9c7]: [Thread[main,5,main]]: setDatabaseName(0,webgoat)
[Server@3044e9c7]: [Thread[main,5,main]]: checkRunning(false) entered
[Server@3044e9c7]: [Thread[main,5,main]]: checkRunning(false) exited
[Server@3044e9c7]: [Thread[main,5,main]]: setDatabasePath(0,/root/.webgoat-8.0.0.M21//data/webgoat)
[Server@3044e9c7]: [Thread[main,5,main]]: checkRunning(false) entered
[Server@3044e9c7]: [Thread[main,5,main]]: checkRunning(false) exited
[Server@3044e9c7]: [Thread[main,5,main]]: setDaemon(true)
[Server@3044e9c7]: [Thread[main,5,main]]: setTrace(false)
[Server@3044e9c7]: [Thread[main,5,main]]: setSilent(true)
[Server@3044e9c7]: Initiating startup sequence...
[Server@3044e9c7]: Server socket opened successfully in 4 ms.
2018-06-30 17:16:39.931  INFO 3733 --- [erver @3044e9c7] hsqldb.db.HSQLDB6451447B68.ENGINE        : Checkpoint start
2018-06-30 17:16:39.932  INFO 3733 --- [erver @3044e9c7] hsqldb.db.HSQLDB6451447B68.ENGINE        : checkpointClose start
2018-06-30 17:16:39.933  INFO 3733 --- [erver @3044e9c7] hsqldb.db.HSQLDB6451447B68.ENGINE        : checkpointClose synched
2018-06-30 17:16:39.935  INFO 3733 --- [erver @3044e9c7] hsqldb.db.HSQLDB6451447B68.ENGINE        : checkpointClose script done
2018-06-30 17:16:39.940  INFO 3733 --- [erver @3044e9c7] hsqldb.db.HSQLDB6451447B68.ENGINE        : checkpointClose end
2018-06-30 17:16:39.941  INFO 3733 --- [erver @3044e9c7] hsqldb.db.HSQLDB6451447B68.ENGINE        : Checkpoint end - txts: 1
[Server@3044e9c7]: Database [index=0, id=0, db=file:/root/.webgoat-8.0.0.M21//data/webgoat, alias=webgoat] opened successfully in 345 ms.
[Server@3044e9c7]: Startup sequence completed in 351 ms.
[Server@3044e9c7]: 2018-06-30 17:16:39.953 HSQLDB server 2.3.4 is online on port 9001
[Server@3044e9c7]: To close normally, connect and execute SHUTDOWN SQL
[Server@3044e9c7]: From command line, use [Ctrl]+[C] to abort abruptly
2018-06-30 17:16:41.283  INFO 3733 --- [           main] j.LocalContainerEntityManagerFactoryBean : Building JPA container EntityManagerFactory for persistence unit 'default'
2018-06-30 17:16:41.305  INFO 3733 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
2018-06-30 17:16:41.406  INFO 3733 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {5.0.12.Final}
2018-06-30 17:16:41.408  INFO 3733 --- [           main] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
2018-06-30 17:16:41.410  INFO 3733 --- [           main] org.hibernate.cfg.Environment            : HHH000021: Bytecode provider name : javassist
2018-06-30 17:16:41.437  WARN 3733 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
[Server@3044e9c7]: Initiating shutdown sequence...
[Server@3044e9c7]: Shutdown sequence completed in 4 ms.
[Server@3044e9c7]: 2018-06-30 17:16:41.449 SHUTDOWN : System.exit() was not called
2018-06-30 17:16:41.454  INFO 3733 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2018-06-30 17:16:41.528  INFO 3733 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-06-30 17:16:41.536 ERROR 3733 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630) ~[spring-beans-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312) ~[spring-beans-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308) ~[spring-beans-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1080) ~[spring-context-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857) ~[spring-context-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.12.RELEASE.jar!/:1.5.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.12.RELEASE.jar!/:1.5.12.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.12.RELEASE.jar!/:1.5.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.12.RELEASE.jar!/:1.5.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.12.RELEASE.jar!/:1.5.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.12.RELEASE.jar!/:1.5.12.RELEASE]
	at org.owasp.webgoat.StartWebGoat.main(StartWebGoat.java:38) [classes!/:8.0.0.M21]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [webgoat-server-8.0.0.M21.jar:8.0.0.M21]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [webgoat-server-8.0.0.M21.jar:8.0.0.M21]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [webgoat-server-8.0.0.M21.jar:8.0.0.M21]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [webgoat-server-8.0.0.M21.jar:8.0.0.M21]
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.hibernate.boot.spi.XmlMappingBinderAccess.<init>(XmlMappingBinderAccess.java:43) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.boot.MetadataSources.<init>(MetadataSources.java:87) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:179) ~[hibernate-entitymanager-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:149) ~[hibernate-entitymanager-5.0.12.Final.jar!/:5.0.12.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:54) ~[spring-orm-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:360) ~[spring-orm-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:384) ~[spring-orm-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:371) ~[spring-orm-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:336) ~[spring-orm-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1688) ~[spring-beans-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626) ~[spring-beans-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	... 24 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[na:na]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) ~[webgoat-server-8.0.0.M21.jar:8.0.0.M21]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[na:na]

**Comment by nbaars** [comment]
@sharmaaddy you need to use the following command:

```
java --add-modules java.xml.bind -jar webgoat-server-8.0.0.VERSION.jar
```

I've updated the `README.md` in the develop branch. Can you try again?

**Comment by EphremG** [comment]
@nbaars 
I had the same issue and now solved with the command you provided. Thanks

**Comment by scotbellamy** [comment]
I have the same problem on M24.  I also tried cloning, building running with the same error.  I'm running OpenJDK 11 on Macbook Pro.  java.xml.bind does not exist in JDK 11.  Any ideas about how to resolve?
