### ISSUE TITLE
Unable to Run Webgoat

### ISSUE THREAD

**Issue by sharmaaddy** [WebGoat/WebGoat#500]
Hello Team,

With some help I was able to install webgoat 8 but then I am not getting the screen to use it on localhost:8080. And while i attempt to access the webgoat page this is what i see on the command line :+1: 

2018-07-05 23:47:28.944  INFO 2943 --- [           main] org.owasp.webgoat.StartWebGoat           : Started StartWebGoat in 33.711 seconds (JVM running for 35.872)
2018-07-05 23:49:19.013  INFO 2943 --- [.1-8080-exec-10] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:426) ~[tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:687) ~[tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]

org.hsqldb.HsqlException: Client driver version greater than '-1195.-72.-58.-56' is required.  HSQLDB server version is '2.3.4'
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.server.ServerConnection.init(Unknown Source)
	at org.hsqldb.server.ServerConnection.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:844)
org.hsqldb.HsqlException: Client driver version greater than '-1195.-72.-58.-56' is required.  HSQLDB server version is '2.3.4'
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.server.ServerConnection.init(Unknown Source)
	at org.hsqldb.server.ServerConnection.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:844)
org.hsqldb.HsqlException: Client driver version greater than '-1195.-72.-58.-56' is required.  HSQLDB server version is '2.3.4'
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.server.ServerConnection.init(Unknown Source)
	at org.hsqldb.server.ServerConnection.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:844)
org.hsqldb.HsqlException: Client driver version greater than '-1195.-72.-58.-56' is required.  HSQLDB server version is '2.3.4'
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.server.ServerConnection.init(Unknown Source)
	at org.hsqldb.server.ServerConnection.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:844)
org.hsqldb.HsqlException: Client driver version greater than '-1195.-72.-58.-56' is required.  HSQLDB server version is '2.3.4'
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.server.ServerConnection.init(Unknown Source)
	at org.hsqldb.server.ServerConnection.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:844)
org.hsqldb.HsqlException: Client driver version greater than '-1195.-72.-58.-56' is required.  HSQLDB server version is '2.3.4'
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.server.ServerConnection.init(Unknown Source)
	at org.hsqldb.server.ServerConnection.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:844)
org.hsqldb.HsqlException: Client driver version greater than '-1195.-72.-58.-56' is required.  HSQLDB server version is '2.3.4'
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.server.ServerConnection.init(Unknown Source)
	at org.hsqldb.server.ServerConnection.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:844)
org.hsqldb.HsqlException: Client driver version greater than '-1195.-72.-58.-56' is required.  HSQLDB server version is '2.3.4'
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.server.ServerConnection.init(Unknown Source)
	at org.hsqldb.server.ServerConnection.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:844)
org.hsqldb.HsqlException: Client driver version greater than '-1195.-72.-58.-56' is required.  HSQLDB server version is '2.3.4'
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.server.ServerConnection.init(Unknown Source)
	at org.hsqldb.server.ServerConnection.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:844)
org.hsqldb.HsqlException: Client driver version greater than '-1195.-72.-58.-56' is required.  HSQLDB server version is '2.3.4'
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.server.ServerConnection.init(Unknown Source)
	at org.hsqldb.server.ServerConnection.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:844)

Kindly help.

**Comment by nbaars** [comment]
@sharmaaddy which version of WebGoat did you download, v8.0.0.M21?

**Comment by sharmaaddy** [comment]
Yes exactly.
Thank you for your help.

**Comment by boredwookie** [comment]
I'm experiencing this same issue on Ubuntu 18.04 with the openjdk-11-jre-headless package installed. Is there additional guidance for how to overcome this issue?

**Comment by boredwookie** [comment]
I was able to get this to work- my problem was forgetting to visit http://<ip.address>:8080/WebGoat/attack. Instead I was only visiting http://<ip.address>:8080. Sorry about the confusion.
