### ISSUE TITLE
webgoat and webwolf fail to start via docker-compose steps

### ISSUE THREAD

**Issue by PWx21** [WebGoat/WebGoat#526]
Webgoat and webwolf fail to boot when running the docker-compose steps in the Readme:
```
$ curl https://raw.githubusercontent.com/WebGoat/WebGoat/develop/docker-compose.yml | docker-compose -f - up
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   639  100   639    0     0   1858      0 --:--:-- --:--:-- --:--:--  1862
Creating network "peter_default" with the default driver
Pulling webgoat (webgoat/webgoat-8.0:)...
latest: Pulling from webgoat/webgoat-8.0
f2aa67a397c4: Pull complete
a44ea3e7c4ff: Pull complete
8ffd93428115: Pull complete
bd00e3c2b114: Pull complete
342f54931737: Pull complete
fee0b21f15e0: Pull complete
2673b10d9d04: Pull complete
7de39eaff016: Pull complete
30fb8f76b8a2: Pull complete
Digest: sha256:bc09fe2e0721dfaeee79364115aeedf2174cce0947b9ae5fe7c33312ee019a4e
Status: Downloaded newer image for webgoat/webgoat-8.0:latest
Pulling webwolf (webgoat/webwolf:)...
latest: Pulling from webgoat/webwolf
f2aa67a397c4: Already exists
a44ea3e7c4ff: Already exists
8ffd93428115: Already exists
bd00e3c2b114: Already exists
342f54931737: Already exists
fee0b21f15e0: Already exists
ab6bc73c7974: Pull complete
29689aa901c4: Pull complete
Digest: sha256:c9c7ca2e5ea7645af5871ca30e4b5b606aa912cbb64e5ccab0d220572beb3b87
Status: Downloaded newer image for webgoat/webwolf:latest
Creating peter_webwolf_1 ... done
Creating peter_webgoat_1 ... done
Attaching to peter_webwolf_1, peter_webgoat_1
webgoat_1  |
webgoat_1  |   .   ____          _            __ _ _
webgoat_1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
webgoat_1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
webgoat_1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
webgoat_1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
webgoat_1  |  =========|_|==============|___/=/_/_/_/
webgoat_1  |  :: Spring Boot ::       (v1.5.12.RELEASE)
webgoat_1  |
webwolf_1  |
webwolf_1  |   .   ____          _            __ _ _
webwolf_1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
webwolf_1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
webwolf_1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
webwolf_1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
webwolf_1  |  =========|_|==============|___/=/_/_/_/
webwolf_1  |  :: Spring Boot ::       (v1.5.12.RELEASE)
webwolf_1  |
webgoat_1  | 2018-10-03 17:28:31.068  INFO 1 --- [           main] org.owasp.webgoat.StartWebGoat           : Starting StartWebGoat v8.0.0.M21 on ff2453e983e6 with PID 1 (/home/webgoat/webgoat.jar started by webgoat in /)
webgoat_1  | 2018-10-03 17:28:31.076 DEBUG 1 --- [           main] org.owasp.webgoat.StartWebGoat           : Running with Spring Boot v1.5.12.RELEASE, Spring v4.3.16.RELEASE
webgoat_1  | 2018-10-03 17:28:31.087  INFO 1 --- [           main] org.owasp.webgoat.StartWebGoat           : No active profile set, falling back to default profiles: default
webwolf_1  | 2018-10-03 17:28:31.245  INFO 1 --- [           main] org.owasp.webwolf.WebWolf                : Starting WebWolf v8.0.0.M21 on 659359a496a7 with PID 1 (/home/webwolf/webwolf.jar started by webwolf in /)
webwolf_1  | 2018-10-03 17:28:31.267 DEBUG 1 --- [           main] org.owasp.webwolf.WebWolf                : Running with Spring Boot v1.5.12.RELEASE, Spring v4.3.16.RELEASE
webwolf_1  | 2018-10-03 17:28:31.273  INFO 1 --- [           main] org.owasp.webwolf.WebWolf                : No active profile set, falling back to default profiles: default
webwolf_1  | 2018-10-03 17:28:32.105  INFO 1 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@2328c243: startup date [Wed Oct 03 17:28:32 UTC 2018]; root of context hierarchy
webgoat_1  | 2018-10-03 17:28:32.115  INFO 1 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@4ee285c6: startup date [Wed Oct 03 17:28:32 UTC 2018]; root of context hierarchy
webwolf_1  | 2018-10-03 17:28:37.601  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$ac782f7b] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
webgoat_1  | 2018-10-03 17:28:38.750  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$28feb5c] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
webwolf_1  | 2018-10-03 17:28:39.022  INFO 1 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 9090 (http)
webwolf_1  | 2018-10-03 17:28:39.129  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
webwolf_1  | 2018-10-03 17:28:39.129  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.29
webwolf_1  | 2018-10-03 17:28:39.387  INFO 1 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
webwolf_1  | 2018-10-03 17:28:39.387  INFO 1 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 7284 ms
webgoat_1  | 2018-10-03 17:28:39.546 ERROR 1 --- [           main] o.s.b.b.PropertiesConfigurationFactory   : Properties configuration failed validation
webgoat_1  | 2018-10-03 17:28:39.550 ERROR 1 --- [           main] o.s.b.b.PropertiesConfigurationFactory   : Field error in object 'server' on field 'address': rejected value [0.0.0.0,0.0.0.0]; codes [typeMismatch.server.address,typeMismatch.address,typeMismatch.java.net.InetAddress,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [server.address,address]; arguments []; default message [address]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.net.InetAddress' for property 'address'; nested exception is java.lang.IllegalArgumentException: Cannot locate host]
webgoat_1  | 2018-10-03 17:28:39.553  WARN 1 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletContainer' defined in org.owasp.webgoat.WebGoat: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverProperties': Could not bind properties to ServerProperties (prefix=server, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is org.springframework.validation.BindException: org.springframework.boot.bind.RelaxedDataBinder$RelaxedBeanPropertyBindingResult: 1 errors
webgoat_1  | Field error in object 'server' on field 'address': rejected value [0.0.0.0,0.0.0.0]; codes [typeMismatch.server.address,typeMismatch.address,typeMismatch.java.net.InetAddress,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [server.address,address]; arguments []; default message [address]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.net.InetAddress' for property 'address'; nested exception is java.lang.IllegalArgumentException: Cannot locate host]
webgoat_1  | 2018-10-03 17:28:39.590  INFO 1 --- [           main] utoConfigurationReportLoggingInitializer :
webgoat_1  |
webgoat_1  | Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
webgoat_1  | 2018-10-03 17:28:39.596 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :
webgoat_1  |
webgoat_1  | ***************************
webgoat_1  | APPLICATION FAILED TO START
webgoat_1  | ***************************
webgoat_1  |
webgoat_1  | Description:
webgoat_1  |
webgoat_1  | Binding to target org.springframework.boot.autoconfigure.web.ServerProperties@3d6f0054 failed:
webgoat_1  |
webgoat_1  |     Property: server.address
webgoat_1  |     Value: 0.0.0.0,0.0.0.0
webgoat_1  |     Reason: Failed to convert property value of type 'java.lang.String' to required type 'java.net.InetAddress' for property 'address'; nested exception is java.lang.IllegalArgumentException: Cannot locate host
webgoat_1  |
webgoat_1  |
webgoat_1  | Action:
webgoat_1  |
webgoat_1  | Update your application's configuration
...
peter_webgoat_1 exited with code 1
webwolf_1  | 2018-10-03 17:28:40.728 ERROR 1 --- [           main] o.a.tomcat.jdbc.pool.ConnectionPool      : Unable to create initial connections of pool.
webwolf_1  |
webwolf_1  | java.sql.SQLTransientConnectionException: java.net.ConnectException: Connection refused (Connection refused)
webwolf_1  | 	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
webwolf_1  | 	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
webwolf_1  | 	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
webwolf_1  | 	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
webwolf_1  | 	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
webwolf_1  | 	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:319) ~[tomcat-jdbc-8.5.29.jar!/:na]
webwolf_1  | 	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:212) ~[tomcat-jdbc-8.5.29.jar!/:na]
webwolf_1  | 	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:736) [tomcat-jdbc-8.5.29.jar!/:na]
webwolf_1  | 	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:668) [tomcat-jdbc-8.5.29.jar!/:na]
webwolf_1  | 	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:483) [tomcat-jdbc-8.5.29.jar!/:na]
webwolf_1  | 	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:154) [tomcat-jdbc-8.5.29.jar!/:na]
webwolf_1  | 	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:118) [tomcat-jdbc-8.5.29.jar!/:na]
webwolf_1  | 	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:107) [tomcat-jdbc-8.5.29.jar!/:na]
webwolf_1  | 	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:131) [tomcat-jdbc-8.5.29.jar!/:na]
webwolf_1  | 	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111) [spring-jdbc-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
...
peter_webwolf_1 exited with code 1
```
Pulling out I think the important line: `...Field error in object 'server' on field 'address': rejected value [0.0.0.0,0.0.0.0];...` I wasn't originally sure why there were two 0.0.0.0 values there.
But I saw that In the docker-compose.yml file there is the `--server.address=0.0.0.0` flag for webwolf.
I changed the value in the yml file to confirm it's adding itself to the value (instead of I assume replacing the value), and it did - example:
```
webgoat_1  |     Property: server.address
webgoat_1  |     Value: 0.0.0.0,127.0.0.1
```
I don't know where that default value is defined, I suppose in the docker image.
I tried to use single quotes around the address in the flag and that didn't change anything; The error/rejected value still looked like `[0.0.0.0,0.0.0.0]`

Removing the flag for `--server.address=0.0.0.0` in the docker-compose.yml file in the webgoat block allows webgoat to startup. I was able to hit http://localhost:8080/WebGoat/login#lesson/WebWolfIntroduction.lesson successfully. Though _webwolf_ still wasn't able to start, returning/exiting with the same connection error as above.

I'd create a PR to remove that flag which at least gets it partially working, but I figure the better move is to fix the underlying issue of it not accepting alternate values - and I don't know where to fix that, though I'd accept direction.

**Comment by itsbriany** [comment]
I tried that too and it looks like the develop branch is not working with docker.

My workaround was execute docker-compose from the master branch.

**Comment by niania0** [comment]
down the image
and then run the two sh
webgoat.sh
#! /bin/bash
nohup docker run -p 8080:8080 -t webgoat/webgoat-8.0

webwofl.sh
#! /bin/bash
WEBGOAT_SERVER_ADDRESS=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" `docker ps | grep webgoat | awk '{print $1}'`)

nohup docker run -e webgoat.server.address=${WEBGOAT_SERVER_ADDRESS} -t -p 9090:9090 webgoat/webwolf /home/webwolf/run.sh

**Comment by nbaars** [comment]
In M22 we received a pull request for following the normal Docker practices so this should be fixed in the M22 release

**Comment by nbaars** [comment]
Version M23 has been released
