### ISSUE TITLE
(WebGoat-Lessons) Cannot compile sqlinjection parameterized query 

### ISSUE THREAD

**Issue by darsh12** [WebGoat/WebGoat#537]
Hi,
I've been trying to compile Stage 2 of Lab: SQL Injection to no avail and I keep on getting the same error when i edit the Login file.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project sql-injection: Compilation failure
[ERROR] /home/NETID/darshp/Desktop/WebGoat-7.0.1/WebGoat-Lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/sqlinjection/LoginSqlInjection.java:[131,17] cannot find symbol
[ERROR] symbol:   class PreparedStatement
[ERROR] location: class org.owasp.webgoat.plugin.sqlinjection.LoginSqlInjection
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :sql-injection
```

with `mvn -e pacakge`

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:47 min
[INFO] Finished at: 2018-11-15T12:37:44-08:00
[INFO] Final Memory: 35M/279M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project sql-injection: Compilation failure
[ERROR] /home/NETID/darshp/Desktop/WebGoat-7.0.1/WebGoat-Lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/sqlinjection/LoginSqlInjection.java:[131,17] cannot find symbol
[ERROR] symbol:   class PreparedStatement
[ERROR] location: class org.owasp.webgoat.plugin.sqlinjection.LoginSqlInjection
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project sql-injection: Compilation failure
/home/NETID/darshp/Desktop/WebGoat-7.0.1/WebGoat-Lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/sqlinjection/LoginSqlInjection.java:[131,17] cannot find symbol
  symbol:   class PreparedStatement
  location: class org.owasp.webgoat.plugin.sqlinjection.LoginSqlInjection

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/home/NETID/darshp/Desktop/WebGoat-7.0.1/WebGoat-Lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/sqlinjection/LoginSqlInjection.java:[131,17] cannot find symbol
  symbol:   class PreparedStatement
  location: class org.owasp.webgoat.plugin.sqlinjection.LoginSqlInjection

	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:858)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :sql-injection
```

**Comment by nbaars** [comment]
This concerns version 7, we are no longer actively working on 7 due to time constraints and our focus on version 8
