### ISSUE TITLE
Test failure in XXE (German output compared with English output fails)

### ISSUE THREAD

**Issue by hoschmi** [WebGoat/WebGoat#585]
Dear all,

I checked out the develop branch and try to build it on a Manjaro Linux system (German locale)
using Java 11. The build process fails in the XXE. As far as I can see, my system produces a German output, whereas English output is expected. Any ideas? See the -e stack trace below.

Best regards,
Holger

[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.753 s <<< FAILURE! - in org.owasp.webgoat.plugin.BlindSendFileAssignmentTest
[ERROR] wrongXmlShouldGiveErrorBack(org.owasp.webgoat.plugin.BlindSendFileAssignmentTest)  Time elapsed: 0.045 s  <<< FAILURE!
java.lang.AssertionError: 
JSON path "$.output"
Expected: is "javax.xml.bind.UnmarshalException\n - with linked exception:\n[javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,22]\nMessage: The element type \\"text\\" must be terminated by the matching end-tag \\"<\/text>\\".]"
     but: was "javax.xml.bind.UnmarshalException\n - with linked exception:\n[javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,22]\nMessage: Elementtyp \\"text\\" muss mit dem entsprechenden Endtag \\"<\/text>\\" beendet werden.]"
	at org.owasp.webgoat.plugin.BlindSendFileAssignmentTest.wrongXmlShouldGiveErrorBack(BlindSendFileAssignmentTest.java:72)

[INFO] Running org.owasp.webgoat.plugin.ContentTypeAssignmentTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.101 s - in org.owasp.webgoat.plugin.ContentTypeAssignmentTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   BlindSendFileAssignmentTest.wrongXmlShouldGiveErrorBack:72 JSON path "$.output"
Expected: is "javax.xml.bind.UnmarshalException\n - with linked exception:\n[javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,22]\nMessage: The element type \\"text\\" must be terminated by the matching end-tag \\"<\/text>\\".]"
     but: was "javax.xml.bind.UnmarshalException\n - with linked exception:\n[javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,22]\nMessage: Elementtyp \\"text\\" muss mit dem entsprechenden Endtag \\"<\/text>\\" beendet werden.]"
[INFO] 
[ERROR] Tests run: 12, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for WebGoat Parent Pom v8.0.0-SNAPSHOT:
[INFO] 
[INFO] WebGoat Parent Pom ................................. SUCCESS [  0.214 s]
[INFO] webgoat-container .................................. SUCCESS [ 12.005 s]
[INFO] webgoat-plugins-parent ............................. SUCCESS [  0.388 s]
[INFO] bypass-restrictions ................................ SUCCESS [  8.616 s]
[INFO] challenge .......................................... SUCCESS [  2.313 s]
[INFO] client-side-filtering .............................. SUCCESS [  9.122 s]
[INFO] cross-site-scripting ............................... SUCCESS [  4.424 s]
[INFO] html-tampering ..................................... SUCCESS [  0.274 s]
[INFO] http-basics ........................................ SUCCESS [  0.323 s]
[INFO] cia ................................................ SUCCESS [  9.153 s]
[INFO] chrome-dev-tools ................................... SUCCESS [  0.268 s]
[INFO] http-proxies ....................................... SUCCESS [  2.048 s]
[INFO] insecure-login ..................................... SUCCESS [  0.279 s]
[INFO] insecure-deserialization ........................... SUCCESS [  0.297 s]
[INFO] jwt ................................................ SUCCESS [  9.468 s]
[INFO] sql-injection ...................................... SUCCESS [  9.673 s]
[INFO] xxe ................................................ FAILURE [ 10.079 s]
[INFO] idor ............................................... SKIPPED
[INFO] vulnerable-components .............................. SKIPPED
[INFO] webgoat-introduction ............................... SKIPPED
[INFO] webwolf-introduction ............................... SKIPPED
[INFO] auth-bypass ........................................ SKIPPED
[INFO] missing-function-ac ................................ SKIPPED
[INFO] csrf ............................................... SKIPPED
[INFO] password-reset ..................................... SKIPPED
[INFO] ssrf ............................................... SKIPPED
[INFO] secure-passwords ................................... SKIPPED
[INFO] webgoat-server ..................................... SKIPPED
[INFO] webwolf ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:19 min
[INFO] Finished at: 2019-04-04T20:15:58+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project xxe: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/schmidt/git/WebGoat/webgoat-lessons/xxe/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project xxe: There are test failures.

Please refer to /home/schmidt/git/WebGoat/webgoat-lessons/xxe/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /home/schmidt/git/WebGoat/webgoat-lessons/xxe/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
    at org.apache.maven.plugin.surefire.SurefireHelper.throwException (SurefireHelper.java:240)
    at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution (SurefireHelper.java:112)
    at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary (SurefirePlugin.java:364)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked (AbstractSurefireMojo.java:1052)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:868)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)

**Comment by Tobias-Melzer** [comment]
The test is fixed and i have created a pull request (fixed test).

**Comment by Pino-HD** [comment]
After I fixed this problem , i have a new trouble.
---------------------------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.141 sec - in org.owasp.webgoat.plugin.BlindSendFileAssignmentTest
Running org.owasp.webgoat.plugin.ContentTypeAssignmentTest
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.25 sec <<< FAILURE! - in org.owasp.webgoat.plugin.ContentTypeAssignmentTest
workingAttack(org.owasp.webgoat.plugin.ContentTypeAssignmentTest)  Time elapsed: 0.125 sec  <<< FAILURE!
java.lang.AssertionError: 
JSON path "$.feedback"
Expected: is "Congratulations. You have successfully completed the assignment."
     but: was "You are posting XML but there is no XXE attack performed"
	at org.owasp.webgoat.plugin.ContentTypeAssignmentTest.workingAttack(ContentTypeAssignmentTest.java:52)

Running org.owasp.webgoat.plugin.SimpleXXETest
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.109 sec <<< FAILURE! - in org.owasp.webgoat.plugin.SimpleXXETest
workingAttack(org.owasp.webgoat.plugin.SimpleXXETest)  Time elapsed: 0.031 sec  <<< FAILURE!
java.lang.AssertionError: 
JSON path "$.feedback"
Expected: is "Congratulations. You have successfully completed the assignment."
     but: was "Sorry the solution is not correct, please try again."
	at org.owasp.webgoat.plugin.SimpleXXETest.workingAttack(SimpleXXETest.java:37)
------------------------------------------------------------------------------------------------------
have you got such problem? @Tobias-Melzer

**Comment by nbaars** [comment]
Fixed in the release v8.0.0.M25
