### ISSUE TITLE
https://github.com/WebGoat/WebGoat/blob/master/README.MD don't work on Windows 7

### ISSUE THREAD

**Issue by davewichers** [WebGoat/WebGoat#62]
These instructions download, build, and deploy instructions worked like a champ. I love it when things like this 'just work'.

However, when I actually start running WebGoat, using: Option #1: Using the Maven-Tomcat Plugin

The maven tomcat7:run-war goal runs the project in an embedded tomcat:

cd WebGoat
mvn -pl webgoat-container tomcat7:run-war

I get the following error. I don't understand how this could be a permissions error because I installed and built and ran all this with the same user ID. Am I doing something wrong? Or is there a bug in WebGoat?

Thanks, Dave

[INFO] Initializing main webgoat servlet
[ERROR] Loading plugins failed
org.owasp.webgoat.plugins.PluginLoadingFailure: Property file detected, but unable to copy the properties
        at org.owasp.webgoat.plugins.Plugin.copyProperties(Plugin.java:96)
        at org.owasp.webgoat.plugins.Plugin.loadFiles(Plugin.java:80)
        at org.owasp.webgoat.plugins.PluginsLoader.processPlugins(PluginsLoader.java:86)
        at org.owasp.webgoat.plugins.PluginsLoader.loadPlugins(PluginsLoader.java:49)
        at org.owasp.webgoat.plugins.PluginsLoader.run(PluginsLoader.java:113)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.NoSuchFileException: C:\dwichers\WebGoat\webgoat-container\target\webgoat-container-7.0-SNAPSHOT\plugin_extracted\plugin\i18n\WebGoatLabels_ru.properties
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
        at java.nio.file.Files.newByteChannel(Files.java:317)
        at java.nio.file.Files.newByteChannel(Files.java:363)
        at java.nio.file.Files.readAllBytes(Files.java:2981)
        at org.owasp.webgoat.plugins.Plugin.copyProperties(Plugin.java:90)
        ... 11 more
Sep 14, 2015 2:58:49 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Sep 14, 2015 3:00:45 PM org.apache.jasper.compiler.TldLocationsCache tldScanJar
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.

Which I think is then causing this error:

[ERROR] Loading plugins failed
org.owasp.webgoat.plugins.PluginLoadingFailure: Property file detected, but unable to copy the properties
        at org.owasp.webgoat.plugins.Plugin.copyProperties(Plugin.java:96)
        at org.owasp.webgoat.plugins.Plugin.loadFiles(Plugin.java:80)
        at org.owasp.webgoat.plugins.PluginsLoader.processPlugins(PluginsLoader.java:86)
        at org.owasp.webgoat.plugins.PluginsLoader.loadPlugins(PluginsLoader.java:49)
        at org.owasp.webgoat.plugins.PluginsLoader.run(PluginsLoader.java:113)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.NoSuchFileException: C:\dwichers\WebGoat\webgoat-container\target\webgoat-container-7.0-SNAPSHOT\plugin_extracted\plugin\i18n\WebGoatLabels_fr.properties
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
        at java.nio.file.Files.newByteChannel(Files.java:317)
        at java.nio.file.Files.newByteChannel(Files.java:363)
        at java.nio.file.Files.readAllBytes(Files.java:2981)
        at org.owasp.webgoat.plugins.Plugin.copyProperties(Plugin.java:90)
        ... 11 more

by the way. 

When trying Option #2 I get a different error:

SEVERE: Exception fixing docBase for context [/WebGoat] java.io.FileNotFoundException: C:\dwichers\WebGoat\webgoat-container\target\.extract\webapps\WebGoat.war (The system cannot find the file specified)

And indeed, that file is not in that directory.

p.s. The quick start using the .sh script for Mac worked like a champ.

**Comment by nbaars** [comment]
same issue as https://github.com/WebGoat/WebGoat/issues/71
