### ISSUE TITLE
Exception in thread error when running the docker image

### ISSUE THREAD

**Issue by 0xShin** [WebGoat/WebGoat#742]
```
root@Test:/home/shin# docker run -p 8080:8080 -t webgoat/webgoat-8.0
Exception in thread "main" java.lang.IllegalStateException: Failed to create unpack folder in directory '/tmp'
        at org.springframework.boot.loader.archive.JarFileArchive.createUnpackFolder(JarFileArchive.java:146)
        at org.springframework.boot.loader.archive.JarFileArchive.getTempUnpackFolder(JarFileArchive.java:132)
        at org.springframework.boot.loader.archive.JarFileArchive.getUnpackedNestedArchive(JarFileArchive.java:122)
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:106)
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:87)
        at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:69)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)```

**Comment by zubcevic** [comment]
You should follow the instruction in the README.MD on how to run it in docker. The above startup arguments are incorrect

**Comment by Stegoo** [comment]
When running the command `docker run -d -p 8080:8080 -p 9090:9090 -e TZ=Australia/Sydney webgoat/goatandwolf`

Got the same error: `Starting nginx: nginx failed!
Exception in thread "main" java.lang.IllegalStateException: Failed to create unpack folder in directory '/tmp'
	at org.springframework.boot.loader.archive.JarFileArchive.createUnpackFolder(JarFileArchive.java:146)
	at org.springframework.boot.loader.archive.JarFileArchive.getTempUnpackFolder(JarFileArchive.java:132)
	at org.springframework.boot.loader.archive.JarFileArchive.getUnpackedNestedArchive(JarFileArchive.java:122)
	at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:106)
	at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:87)
	at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:69)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)`

**Comment by zubcevic** [comment]
It looks like you have some docker set up issues or additional security settings. Your command works fine for me. You can use a memory file system for /tmp. 
Try: docker run -d --tmpfs /tmp -p 8080:8080 -p 9090:9090 -e TZ=Australia/Sydney webgoat/goatandwolf
