### ISSUE TITLE
Cannot get WebWolf to start on Docker

### ISSUE THREAD

**Issue by marshalmiller** [WebGoat/WebGoat#744]
This is a continuation of the issue here: https://github.com/WebGoat/WebGoat/issues/449
Docker containers will not start with WebWolf.

**Comment by marshalmiller** [comment]
.   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.0.RELEASE)[0;39m

2020-01-05 02:37:43.232[0;39m  INFO[0;39m 7[0;39m ---[0;39m [           main][0;39m org.owasp.webwolf.WebWolf               [0;39m :[0;39m Starting WebWolf v8.0.0.M26 on b700bd6398ff with PID 7 (/home/webwolf/webwolf.jar started by webwolf in /)
2020-01-05 02:37:43.248[0;39m DEBUG[0;39m 7[0;39m ---[0;39m [           main][0;39m org.owasp.webwolf.WebWolf               [0;39m :[0;39m Running with Spring Boot v2.2.0.RELEASE, Spring v5.2.0.RELEASE
2020-01-05 02:37:43.249[0;39m  INFO[0;39m 7[0;39m ---[0;39m [           main][0;39m org.owasp.webwolf.WebWolf               [0;39m :[0;39m No active profile set, falling back to default profiles: default
2020-01-05 02:37:44.250[0;39m  INFO[0;39m 7[0;39m ---[0;39m [           main][0;39m .s.d.r.c.RepositoryConfigurationDelegate[0;39m :[0;39m Bootstrapping Spring Data repositories in DEFAULT mode.
2020-01-05 02:37:44.324[0;39m  INFO[0;39m 7[0;39m ---[0;39m [           main][0;39m .s.d.r.c.RepositoryConfigurationDelegate[0;39m :[0;39m Finished Spring Data repository scanning in 66ms. Found 2 repository interfaces.
2020-01-05 02:37:44.797[0;39m  INFO[0;39m 7[0;39m ---[0;39m [           main][0;39m trationDelegate$BeanPostProcessorChecker[0;39m :[0;39m Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-01-05 02:37:45.109[0;39m  INFO[0;39m 7[0;39m ---[0;39m [           main][0;39m o.s.b.w.embedded.tomcat.TomcatWebServer [0;39m :[0;39m Tomcat initialized with port(s): 9090 (http)
2020-01-05 02:37:45.120[0;39m  INFO[0;39m 7[0;39m ---[0;39m [           main][0;39m o.apache.catalina.core.StandardService  [0;39m :[0;39m Starting service [Tomcat]
2020-01-05 02:37:45.121[0;39m  INFO[0;39m 7[0;39m ---[0;39m [           main][0;39m org.apache.catalina.core.StandardEngine [0;39m :[0;39m Starting Servlet engine: [Apache Tomcat/9.0.27]
2020-01-05 02:37:45.182[0;39m  INFO[0;39m 7[0;39m ---[0;39m [           main][0;39m o.a.c.c.C.[Tomcat].[localhost].[/]      [0;39m :[0;39m Initializing Spring embedded WebApplicationContext
2020-01-05 02:37:45.182[0;39m  INFO[0;39m 7[0;39m ---[0;39m [           main][0;39m o.s.web.context.ContextLoader           [0;39m :[0;39m Root WebApplicationContext: initialization completed in 1850 ms
2020-01-05 02:37:45.534[0;39m  INFO[0;39m 7[0;39m ---[0;39m [           main][0;39m o.hibernate.jpa.internal.util.LogHelper [0;39m :[0;39m HHH000204: Processing PersistenceUnitInfo [name: default]
2020-01-05 02:37:45.644[0;39m  INFO[0;39m 7[0;39m ---[0;39m [           main][0;39m org.hibernate.Version                   [0;39m :[0;39m HHH000412: Hibernate Core {5.4.6.Final}
2020-01-05 02:37:45.805[0;39m  INFO[0;39m 7[0;39m ---[0;39m [           main][0;39m o.hibernate.annotations.common.Version  [0;39m :[0;39m HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
2020-01-05 02:37:45.970[0;39m  WARN[0;39m 7[0;39m ---[0;39m [           main][0;39m o.h.e.j.e.i.JdbcEnvironmentInitiator    [0;39m :[0;39m HHH000342: Could not obtain connection to query metadata : java.net.ConnectException: Connection refused (Connection refused)
2020-01-05 02:37:45.984[0;39m  INFO[0;39m 7[0;39m ---[0;39m [           main][0;39m org.hibernate.dialect.Dialect           [0;39m :[0;39m HHH000400: Using dialect: org.hibernate.dialect.HSQLDialect
2020-01-05 02:37:46.578[0;39m  WARN[0;39m 7[0;39m ---[0;39m [           main][0;39m o.h.engine.jdbc.spi.SqlExceptionHelper  [0;39m :[0;39m SQL Error: -1301, SQLState: 08001
2020-01-05 02:37:46.578[0;39m ERROR[0;39m 7[0;39m ---[0;39m [           main][0;39m o.h.engine.jdbc.spi.SqlExceptionHelper  [0;39m :[0;39m java.net.ConnectException: Connection refused (Connection refused)
2020-01-05 02:37:46.582[0;39m  WARN[0;39m 7[0;39m ---[0;39m [           main][0;39m ConfigServletWebServerApplicationContext[0;39m :[0;39m Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution
2020-01-05 02:37:46.585[0;39m  INFO[0;39m 7[0;39m ---[0;39m [           main][0;39m o.apache.catalina.core.StandardService  [0;39m :[0;39m Stopping service [Tomcat]
2020-01-05 02:37:46.603[0;39m  INFO[0;39m 7[0;39m ---[0;39m [           main][0;39m ConditionEvaluationReportLoggingListener[0;39m :[0;39m 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-01-05 02:37:46.609[0;39m ERROR[0;39m 7[0;39m ---[0;39m [           main][0;39m o.s.boot.SpringApplication              [0;39m :[0;39m Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1803) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108) ~[spring-context-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868) ~[spring-context-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.owasp.webwolf.WebWolf.main(WebWolf.java:45) ~[classes!/:8.0.0.M26]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[webwolf.jar:8.0.0.M26]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[webwolf.jar:8.0.0.M26]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[webwolf.jar:8.0.0.M26]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[webwolf.jar:8.0.0.M26]
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:403) ~[spring-orm-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:378) ~[spring-orm-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341) ~[spring-orm-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	... 24 common frames omitted
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl.getIsolatedConnection(DdlTransactionIsolatorNonJtaImpl.java:69) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
	at org.hibernate.tool.schema.internal.exec.ImprovedExtractionContextImpl.getJdbcConnection(ImprovedExtractionContextImpl.java:60) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
	at org.hibernate.tool.schema.extract.internal.SequenceInformationExtractorLegacyImpl.extractMetadata(SequenceInformationExtractorLegacyImpl.java:40) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
	at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.initializeSequences(DatabaseInformationImpl.java:65) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
	at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.<init>(DatabaseInformationImpl.java:59) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
	at org.hibernate.tool.schema.internal.Helper.buildDatabaseInformation(Helper.java:155) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.doMigration(AbstractSchemaMigrator.java:96) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:184) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:73) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:320) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:462) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:935) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58) ~[spring-orm-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365) ~[spring-orm-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:391) ~[spring-orm-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	... 28 common frames omitted
Caused by: java.sql.SQLTransientConnectionException: java.net.ConnectException: Connection refused (Connection refused)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677) ~[java.sql:na]
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189) ~[java.sql:na]
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:154) ~[spring-jdbc-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:145) ~[spring-jdbc-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:205) ~[spring-jdbc-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:169) ~[spring-jdbc-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:180) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl.getIsolatedConnection(DdlTransactionIsolatorNonJtaImpl.java:43) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
	... 42 common frames omitted
Caused by: org.hsqldb.HsqlException: java.net.ConnectException: Connection refused (Connection refused)
	at org.hsqldb.ClientConnection.openConnection(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
	at org.hsqldb.ClientConnection.initConnection(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
	at org.hsqldb.ClientConnection.<init>(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
	... 54 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:591) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:540) ~[na:na]
	at java.base/java.net.Socket.<init>(Socket.java:436) ~[na:na]
	at java.base/java.net.Socket.<init>(Socket.java:213) ~[na:na]
	at org.hsqldb.server.HsqlSocketFactory.createSocket(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
	... 57 common frames omitted

**Comment by zubcevic** [comment]
You cannot run webwolf standalone. So it is best to follow the direction in the Readme.md of the develop branch and pick one of the two suggested options. Or start a webgoat container first with ports 8080 and 9001 available to the local machine.

**Comment by zubcevic** [comment]
https://github.com/WebGoat/WebGoat/blob/develop/README.MD

docker run -d -p 8080:8080 -p 9090:9090 -e TZ=Europe/Amsterdam webgoat/goatandwolf
