### ISSUE TITLE
WebWolf  Could not obtain connection to query metadata : java.net.ConnectException: Connection refused: connect

### ISSUE THREAD

**Issue by anagfar** [WebGoat/WebGoat#750]
HI!

I cannot run webwolf on my windows 10. 

jdk-11.0.6

java -jar C:\..............\webwolf-8.0.0.M26.jar

Some one else have the same error?. Thank you very much indeed..

Gives me the following error:

`  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.0.RELEASE)

2020-01-21 19:15:14.848  INFO 22336 --- [           main] org.owasp.webwolf.WebWolf                : Starting WebWolf v8.0.0.M26 on LAPTOP-APA4L58R with PID 22336 (C:\..........\webwolf-8.0.0.M26.jar started by ......... in C:\...........)
2020-01-21 19:15:14.853 DEBUG 22336 --- [           main] org.owasp.webwolf.WebWolf                : Running with Spring Boot v2.2.0.RELEASE, Spring v5.2.0.RELEASE
2020-01-21 19:15:14.854  INFO 22336 --- [           main] org.owasp.webwolf.WebWolf                : No active profile set, falling back to default profiles: default
2020-01-21 19:15:16.252  INFO 22336 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-01-21 19:15:16.375  INFO 22336 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 107ms. Found 2 repository interfaces.
2020-01-21 19:15:17.164  INFO 22336 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-01-21 19:15:21.153  INFO 22336 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9090 (http)
2020-01-21 19:15:21.166  INFO 22336 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-01-21 19:15:21.167  INFO 22336 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.27]
2020-01-21 19:15:21.246  INFO 22336 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-01-21 19:15:21.247  INFO 22336 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 6301 ms
2020-01-21 19:15:21.719  INFO 22336 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2020-01-21 19:15:21.827  INFO 22336 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {5.4.6.Final}
2020-01-21 19:15:22.032  INFO 22336 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
2020-01-21 19:15:24.289  WARN 22336 --- [           main] o.h.e.j.e.i.JdbcEnvironmentInitiator     : HHH000342: Could not obtain connection to query metadata : java.net.ConnectException: Connection refused: connect
2020-01-21 19:15:24.316  INFO 22336 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.HSQLDialect
2020-01-21 19:15:27.532  WARN 22336 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: -1301, SQLState: 08001
2020-01-21 19:15:27.533 ERROR 22336 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : java.net.ConnectException: Connection refused: connect
2020-01-21 19:15:27.549  WARN 22336 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution
2020-01-21 19:15:27.557  INFO 22336 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-01-21 19:15:27.588  INFO 22336 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-01-21 19:15:27.593 ERROR 22336 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1803) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108) ~[spring-context-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868) ~[spring-context-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
        at org.owasp.webwolf.WebWolf.main(WebWolf.java:45) ~[classes!/:8.0.0.M26]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[webwolf-8.0.0.M26.jar:8.0.0.M26]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[webwolf-8.0.0.M26.jar:8.0.0.M26]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[webwolf-8.0.0.M26.jar:8.0.0.M26]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[webwolf-8.0.0.M26.jar:8.0.0.M26]
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:403) ~[spring-orm-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:378) ~[spring-orm-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341) ~[spring-orm-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        ... 24 common frames omitted
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
        at org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl.getIsolatedConnection(DdlTransactionIsolatorNonJtaImpl.java:69) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
        at org.hibernate.tool.schema.internal.exec.ImprovedExtractionContextImpl.getJdbcConnection(ImprovedExtractionContextImpl.java:60) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
        at org.hibernate.tool.schema.extract.internal.SequenceInformationExtractorLegacyImpl.extractMetadata(SequenceInformationExtractorLegacyImpl.java:40) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
        at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.initializeSequences(DatabaseInformationImpl.java:65) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
        at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.<init>(DatabaseInformationImpl.java:59) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
        at org.hibernate.tool.schema.internal.Helper.buildDatabaseInformation(Helper.java:155) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
        at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.doMigration(AbstractSchemaMigrator.java:96) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:184) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:73) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:320) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:462) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:935) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58) ~[spring-orm-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365) ~[spring-orm-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:391) ~[spring-orm-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        ... 28 common frames omitted
Caused by: java.sql.SQLTransientConnectionException: java.net.ConnectException: Connection refused: connect
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
        at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
        at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
        at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677) ~[java.sql:na]
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189) ~[java.sql:na]
        at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:154) ~[spring-jdbc-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:145) ~[spring-jdbc-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:205) ~[spring-jdbc-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:169) ~[spring-jdbc-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:180) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
        at org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl.getIsolatedConnection(DdlTransactionIsolatorNonJtaImpl.java:43) ~[hibernate-core-5.4.6.Final.jar!/:5.4.6.Final]
        ... 42 common frames omitted
Caused by: org.hsqldb.HsqlException: java.net.ConnectException: Connection refused: connect
        at org.hsqldb.ClientConnection.openConnection(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
        at org.hsqldb.ClientConnection.initConnection(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
        at org.hsqldb.ClientConnection.<init>(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
        ... 54 common frames omitted
Caused by: java.net.ConnectException: Connection refused: connect
        at java.base/java.net.PlainSocketImpl.connect0(Native Method) ~[na:na]
        at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101) ~[na:na]
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[na:na]
        at java.base/java.net.Socket.connect(Socket.java:608) ~[na:na]
        at java.base/java.net.Socket.connect(Socket.java:557) ~[na:na]
        at java.base/java.net.Socket.<init>(Socket.java:453) ~[na:na]
        at java.base/java.net.Socket.<init>(Socket.java:230) ~[na:na]
        at org.hsqldb.server.HsqlSocketFactory.createSocket(Unknown Source) ~[hsqldb-2.3.4.jar!/:2.3.4]
        ... 57 common frames omitted`

**Comment by nbaars** [comment]
@anagfar Did you start WebGoat before launching WebWolf? (they share the same database)

**Comment by anagfar** [comment]
Hi nbaars, first of all thank you for your answer.

I did but didn't worked. I finally found the problem. It works but only if I don't specify a local IP address.. only on localhost by default but if I put --server.address=192.168.xx.xx an IP on my LAN, then webwolf fails..

So now I can get into webwol but cannot use ZAP as a proxy for example because localhost traffic do not get redirect to proxy.. so that is pretty anoying..

Does someone else have this same problem? and then.. how did you solve it?.

Thank you very much
Best regards

**Comment by zubcevic** [comment]
Hi
if you build webgoat and webwolf from the latest develop branch, you will see updated instructions on how to use zap and browser on localhost.
#701

**Comment by anagfar** [comment]
Just one question though, shouldn't webgoat and webwolf work when passing --server.address=IP?

Webgoat lodas fine this way but not webwolf.... Is it the only way? run them in localhost only....

Thank  you very much!

**Comment by zubcevic** [comment]
Maybe you are looking for something like the fix in #749 

With this fix you can deploy WebGoat and WebWolf in a single docker container and use any IP with which you access it or assign it to.

Also you can deploy it on a local Kubernetes cluster or temporarily on a public cloud, like this: https://zubcevicdotcom.wordpress.com/owas-webgoat/deploying-webgoat-on-microsoft-azure-cloud/ 

Or when you have build the jars yourself, you could do:
java -Dfile.encoding=UTF-8 -jar webgoat.jar  --server.address=0.0.0.0  > webgoat.log &

sleep 10
 
java -Dfile.encoding=UTF-8 -jar webwolf.jar --server.address=0.0.0.0 > webwolf.log &
