### ISSUE TITLE
Nodejs middleware error can you please tell me how to fix this

### ISSUE THREAD

**Issue by umeryounas998** [WebGoat/WebGoat#755]
index.js code
const express=require('express');
const socketio=require('socket.io');
const http=require('http');

const PORT=process.env.PORT || 5000;

const router=require('./router');

const app=express();
const server=http.createServer(app);
const io=socketio(server);

app.use(router);

server.listen(PORT,()=> console.log(Server has started on ${PORT}));
router.js code const express =require('express');
const router=express.Router();

router.get('/',(req,res)=>{
res.send('Server is up and running!!');
});

module.exports = router;
error:
E:\ReactApp\server\node_modules\express\lib\application.js:210
throw new TypeError('app.use() requires a middleware function')
^

TypeError: app.use() requires a middleware function
at Function.use (E:\ReactApp\server\node_modules\express\lib\application.js:210:11)
at Object. (E:\ReactApp\server\index.js:14:5)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load (internal/modules/cjs/loader.js:811:32)
at Function.Module._load (internal/modules/cjs/loader.js:723:14)
at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
at internal/main/run_main_module.js:17:11
[nodemon] app crashed - waiting for file changes before starting

**Comment by zubcevic** [comment]
This has nothing to do with WebGoat, so ask somewhere else

**Comment by umeryounas998** [comment]
Cool
