### ISSUE TITLE
Error occurred while starting webgoat-server-8.0.0.M26.jar

### ISSUE THREAD

**Issue by giwon9977** [WebGoat/WebGoat#832]
I'm trying to start webgoat 8.0 server on CMD using command `java -jar webgoat-server-8.0.0.M26.jar`. However, it throws an error as below:
> 17:14:07.191 [main] INFO org.owasp.webgoat.StartWebGoat - Starting WebGoat with args: 
> 
>   .   ____          _            __ _ _
>  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
> ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
>  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
>   '  |____| .__|_| |_|_| |_\__, | / / / /
>  =========|_|==============|___/=/_/_/_/
>  :: Spring Boot ::        (v2.2.0.RELEASE)
> 
> 2020-06-11 17:14:07.767  INFO 5048 --- [           main] org.owasp.webgoat.StartWebGoat           : Starting StartWebGoat v8.0.0.M26 on DESKTOP-ABTN5LN with PID 5048 (D:\webgoat8\webgoat-server-8.0.0.M26.jar started by 박지원 in D:\webgoat8)
> 2020-06-11 17:14:07.768 DEBUG 5048 --- [           main] org.owasp.webgoat.StartWebGoat           : Running with Spring Boot v2.2.0.RELEASE, Spring v5.2.0.RELEASE
> 2020-06-11 17:14:07.769  INFO 5048 --- [           main] org.owasp.webgoat.StartWebGoat           : No active profile set, falling back to default profiles: default
> 2020-06-11 17:14:08.724  INFO 5048 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
> 2020-06-11 17:14:08.813  INFO 5048 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 82ms. Found 2 repository interfaces.
> 2020-06-11 17:14:09.203  INFO 5048 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 2020-06-11 17:14:09.392  WARN 5048 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
> 2020-06-11 17:14:09.410  INFO 5048 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
> 2020-06-11 17:14:09.410  INFO 5048 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1600 ms
> 2020-06-11 17:14:09.515  INFO 5048 --- [           main] org.owasp.webgoat.HSQLDBDatabaseConfig   : Starting internal database on port 9001 ...
> [Server@551a20d6]: [Thread[main,5,main]]: checkRunning(false) entered
> [Server@551a20d6]: [Thread[main,5,main]]: checkRunning(false) exited
> [Server@551a20d6]: [Thread[main,5,main]]: setDatabaseName(0,webgoat)
> [Server@551a20d6]: [Thread[main,5,main]]: checkRunning(false) entered
> [Server@551a20d6]: [Thread[main,5,main]]: checkRunning(false) exited
> [Server@551a20d6]: [Thread[main,5,main]]: setDatabasePath(0,C:\Users\박지원/.webgoat-@project.version@//data/webgoat)
> [Server@551a20d6]: [Thread[main,5,main]]: checkRunning(false) entered
> [Server@551a20d6]: [Thread[main,5,main]]: checkRunning(false) exited
> [Server@551a20d6]: [Thread[main,5,main]]: setDaemon(true)
> [Server@551a20d6]: [Thread[main,5,main]]: checkRunning(false) entered
> [Server@551a20d6]: [Thread[main,5,main]]: checkRunning(false) exited
> [Server@551a20d6]: [Thread[main,5,main]]: setAddress(127.0.0.1)
> [Server@551a20d6]: [Thread[main,5,main]]: setTrace(false)
> [Server@551a20d6]: [Thread[main,5,main]]: setSilent(true)
> [Server@551a20d6]: Initiating startup sequence...
> [Server@551a20d6]: Server socket opened successfully in 3 ms.
> 2020-06-11 17:14:09.697  INFO 5048 --- [erver @551a20d6] hsqldb.db..ENGINE                        : open start - state modified
> 2020-06-11 17:14:09.716  INFO 5048 --- [erver @551a20d6] hsqldb.db..ENGINE                        : checkpointClose start
> 2020-06-11 17:14:09.716  INFO 5048 --- [erver @551a20d6] hsqldb.db..ENGINE                        : checkpointClose synched
> 2020-06-11 17:14:09.724  INFO 5048 --- [erver @551a20d6] hsqldb.db..ENGINE                        : checkpointClose script done
> 2020-06-11 17:14:09.737  INFO 5048 --- [erver @551a20d6] hsqldb.db..ENGINE                        : checkpointClose end
> [Server@551a20d6]: Database [index=0, id=0, db=file:C:\Users\박지원/.webgoat-@project.version@//data/webgoat, alias=webgoat] opened successfully in 204 ms.
> [Server@551a20d6]: Startup sequence completed in 208 ms.
> [Server@551a20d6]: 2020-06-11 17:14:09.739 HSQLDB server 2.3.4 is online on port 9001
> [Server@551a20d6]: To close normally, connect and execute SHUTDOWN SQL
> [Server@551a20d6]: From command line, use [Ctrl]+[C] to abort abruptly
> 2020-06-11 17:14:09.997  INFO 5048 --- [           main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 6.0.6 by Redgate
> 2020-06-11 17:14:10.144  INFO 5048 --- [           main] o.f.c.internal.database.DatabaseFactory  : Database: jdbc:hsqldb:hsql://127.0.0.1:9001/webgoat (HSQL Database Engine 2.3)
> 2020-06-11 17:14:10.180  INFO 5048 --- [           main] o.f.core.internal.command.DbValidate     : Successfully validated 3 migrations (execution time 00:00.021s)
> 2020-06-11 17:14:10.188  INFO 5048 --- [           main] o.f.core.internal.command.DbMigrate      : Current version of schema "container": 2
> 2020-06-11 17:14:10.189  INFO 5048 --- [           main] o.f.core.internal.command.DbMigrate      : Schema "container" is up to date. No migration necessary.
> 2020-06-11 17:14:10.301  INFO 5048 --- [           main] o.f.c.internal.database.DatabaseFactory  : Database: jdbc:hsqldb:hsql://127.0.0.1:9001/webgoat (HSQL Database Engine 2.3)
> 2020-06-11 17:14:10.310  INFO 5048 --- [           main] o.f.core.internal.command.DbValidate     : Successfully validated 9 migrations (execution time 00:00.007s)
> 2020-06-11 17:14:10.315  INFO 5048 --- [           main] o.f.core.internal.command.DbMigrate      : Current version of schema "PUBLIC": 2019.09.26.7
> 2020-06-11 17:14:10.316  INFO 5048 --- [           main] o.f.core.internal.command.DbMigrate      : Schema "PUBLIC" is up to date. No migration necessary.
> 2020-06-11 17:14:10.522  INFO 5048 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
> 2020-06-11 17:14:10.597  INFO 5048 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {5.4.6.Final}
> 2020-06-11 17:14:10.735  INFO 5048 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
> 2020-06-11 17:14:10.940  INFO 5048 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.HSQLDialect
> 2020-06-11 17:14:11.584  INFO 5048 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
> 2020-06-11 17:14:11.591  INFO 5048 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
> 2020-06-11 17:14:12.255  WARN 5048 --- [           main] o.o.webgoat.plugins.CourseConfiguration  : Lesson: webgoat.title has no endpoints, is this intentionally?
> 2020-06-11 17:14:12.298  WARN 5048 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
> 2020-06-11 17:14:12.458  INFO 5048 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@7523a3dc, org.springframework.security.web.context.SecurityContextPersistenceFilter@1a3e8e24, org.springframework.security.web.header.HeaderWriterFilter@513b52af, org.springframework.security.web.authentication.logout.LogoutFilter@ea52184, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@51a18b21, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@1c7350b0, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@2b0dc227, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@2806d6da, org.springframework.security.web.session.SessionManagementFilter@3bed3315, org.springframework.security.web.access.ExceptionTranslationFilter@1115433e, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@57fbc06f]
> 2020-06-11 17:14:14.637  WARN 5048 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'viewResolver' defined in class path resource [org/owasp/webgoat/MvcConfiguration.class]: Unsatisfied dependency expressed through method 'viewResolver' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'thymeleafTemplateEngine' defined in class path resource [org/owasp/webgoat/MvcConfiguration.class]: Unsatisfied dependency expressed through method 'thymeleafTemplateEngine' parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'asciiDoctorTemplateResolver' defined in class path resource [org/owasp/webgoat/MvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.owasp.webgoat.AsciiDoctorTemplateResolver]: Factory method 'asciiDoctorTemplateResolver' threw exception; nested exception is java.lang.ExceptionInInitializerError
> 2020-06-11 17:14:14.638  INFO 5048 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
> [Server@551a20d6]: Initiating shutdown sequence...
> [Server@551a20d6]: Shutdown sequence completed in 1 ms.
> [Server@551a20d6]: 2020-06-11 17:14:14.641 SHUTDOWN : System.exit() was not called
> 2020-06-11 17:14:14.644  INFO 5048 --- [           main] hsqldb.db..ENGINE                        : Database closed
> 2020-06-11 17:14:14.755  INFO 5048 --- [           main] ConditionEvaluationReportLoggingListener : 
> 
> Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
> 2020-06-11 17:14:14.760 ERROR 5048 --- [           main] o.s.boot.SpringApplication               : Application run failed
> 
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'viewResolver' defined in class path resource [org/owasp/webgoat/MvcConfiguration.class]: Unsatisfied dependency expressed through method 'viewResolver' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'thymeleafTemplateEngine' defined in class path resource [org/owasp/webgoat/MvcConfiguration.class]: Unsatisfied dependency expressed through method 'thymeleafTemplateEngine' parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'asciiDoctorTemplateResolver' defined in class path resource [org/owasp/webgoat/MvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.owasp.webgoat.AsciiDoctorTemplateResolver]: Factory method 'asciiDoctorTemplateResolver' threw exception; nested exception is java.lang.ExceptionInInitializerError
> 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:787) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:528) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
> 	at org.owasp.webgoat.StartWebGoat.main(StartWebGoat.java:47) ~[classes!/:8.0.0.M26]
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
> 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[webgoat-server-8.0.0.M26.jar:8.0.0.M26]
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[webgoat-server-8.0.0.M26.jar:8.0.0.M26]
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[webgoat-server-8.0.0.M26.jar:8.0.0.M26]
> 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[webgoat-server-8.0.0.M26.jar:8.0.0.M26]
> Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'thymeleafTemplateEngine' defined in class path resource [org/owasp/webgoat/MvcConfiguration.class]: Unsatisfied dependency expressed through method 'thymeleafTemplateEngine' parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'asciiDoctorTemplateResolver' defined in class path resource [org/owasp/webgoat/MvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.owasp.webgoat.AsciiDoctorTemplateResolver]: Factory method 'asciiDoctorTemplateResolver' threw exception; nested exception is java.lang.ExceptionInInitializerError
> 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:787) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:528) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:874) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:778) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	... 27 common frames omitted
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'asciiDoctorTemplateResolver' defined in class path resource [org/owasp/webgoat/MvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.owasp.webgoat.AsciiDoctorTemplateResolver]: Factory method 'asciiDoctorTemplateResolver' threw exception; nested exception is java.lang.ExceptionInInitializerError
> 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:645) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:625) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:874) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:778) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	... 41 common frames omitted
> Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.owasp.webgoat.AsciiDoctorTemplateResolver]: Factory method 'asciiDoctorTemplateResolver' threw exception; nested exception is java.lang.ExceptionInInitializerError
> 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:640) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	... 55 common frames omitted
> Caused by: java.lang.ExceptionInInitializerError: null
> 	at org.owasp.webgoat.MvcConfiguration.asciiDoctorTemplateResolver(MvcConfiguration.java:107) ~[webgoat-container-8.0.0.M26.jar!/:8.0.0.M26]
> 	at org.owasp.webgoat.MvcConfiguration$$EnhancerBySpringCGLIB$$52d72cf9.CGLIB$asciiDoctorTemplateResolver$11(<generated>) ~[webgoat-container-8.0.0.M26.jar!/:8.0.0.M26]
> 	at org.owasp.webgoat.MvcConfiguration$$EnhancerBySpringCGLIB$$52d72cf9$$FastClassBySpringCGLIB$$655a7fb0.invoke(<generated>) ~[webgoat-container-8.0.0.M26.jar!/:8.0.0.M26]
> 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	at org.owasp.webgoat.MvcConfiguration$$EnhancerBySpringCGLIB$$52d72cf9.asciiDoctorTemplateResolver(<generated>) ~[webgoat-container-8.0.0.M26.jar!/:8.0.0.M26]
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
> 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
> 	... 56 common frames omitted
> Caused by: org.jruby.exceptions.RaiseException: (Errno::ENOENT) file:/C:/Users/?°??§????/AppData/Local/Temp/webgoat-server-8.0.0.M26.jar-spring-boot-libs-2bab1b91-22ff-4dd8-8551-be90097bb18c/asciidoctorj-1.5.8.1.jar!/specifications/open-uri-cached-0.0.5.gemspec
> 	at org.jruby.RubyFile.initialize(org/jruby/RubyFile.java:359) ~[jruby-complete-9.1.17.0.jar:na]
> 	at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1169) ~[jruby-complete-9.1.17.0.jar:na]
> 	at org.jruby.RubyKernel.open(org/jruby/RubyKernel.java:307) ~[jruby-complete-9.1.17.0.jar:na]
> 	at RUBY.data(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/stub_specification.rb:116) ~[na:na]
> 	at RUBY.valid?(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/stub_specification.rb:207) ~[na:na]
> 	at org.jruby.RubyArray.select(org/jruby/RubyArray.java:2566) ~[jruby-complete-9.1.17.0.jar:na]
> 	at RUBY.gemspec_stubs_in(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:752) ~[na:na]
> 	at RUBY.block in map_stubs(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:777) ~[na:na]
> 	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1735) ~[jruby-complete-9.1.17.0.jar:na]
> 	at org.jruby.RubyEnumerable.flat_map(org/jruby/RubyEnumerable.java:877) ~[jruby-complete-9.1.17.0.jar:na]
> 	at RUBY.map_stubs(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:774) ~[na:na]
> 	at RUBY.installed_stubs(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:766) ~[na:na]
> 	at RUBY.stubs(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:834) ~[na:na]
> 	at RUBY.find_by_path(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:1039) ~[na:na]
> 	at RUBY.try_activate(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems.rb:209) ~[na:na]
> 	at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:126) ~[na:na]
> 	at RUBY.<main>(<script>:12) ~[na:na]

This is the version of my Java:
![image](https://user-images.githubusercontent.com/66773292/84363140-3f01ff00-ac09-11ea-9476-530d973401c3.png)

Is there any ideas to fix the error?

PS1, I'm executing `webgoat-server-8.0.0.M26.jar` on `D:\webgoat8` to avoid any multibyte character in directory.

PS2, I tried `java --add-modules java.xml.bind -jar webgoat-server-8.0.0.M26.jar`, and of course, it didn't work throwing error like below:
![image](https://user-images.githubusercontent.com/66773292/84364090-9fde0700-ac0a-11ea-982f-ac08ddf2ba24.png)
I saw that I have to add some dependencies in the Maven project to fix that, but how can I do that only with JAR file?

**Comment by giwon9977** [comment]
**The issue is temporarily solved by downloading the whole source code and executing command `mvn -pl webgoat-server spring-boot:run` on CMD.**
