### ISSUE TITLE
Webgoat not saving registered credentials on docker container

### ISSUE THREAD

**Issue by Sybrid203** [WebGoat/WebGoat#860]
Hey, I've been trying to start webgoat on a container instance. All works great but whenever I close the session and start it up again, my credentials are lost. Basically it starts as a clean-slate all over again. What could be the problem?

I run: `docker run -p 8080:8080 -p 9090:9090 -e TZ=Europe/Amsterdam webgoat/goatandwolf`
it boots up and I can access it through localhost:8080/WebGoat or WebWolf. Awesome.
I register with a user, login, logout, login again just to check it is saved and logout again. 
`docker ps`
output: <docker id> 
`docker stop <docker id>`
**STOPPED**

`docker run -p 8080:8080 -p 9090:9090 -e TZ=Europe/Amsterdam webgoat/goatandwolf`
everything works fine
try to login - fail. username does not exist.

I tried the solution you provided in [https://github.com/WebGoat/WebGoat/issues/457](url), but with no success. 
Thank you so much! 

P.S 
I have access to webgoat@<docker id> after running `docker exec -i -t CONTAINER_ID /bin/bash ` like you suggested in the link above and I can see all the folders - XXE, data, secret.txt, etc. I tried mapping it to .webgoat-8.1.0 since `.webgoat-v8.0.0.M14` is not valid anymore, but I am resulted with a long long Java error that I am unable to decipher:

**COMMAND:** `docker run -p 8080:8080 -it -v /tmp/webgoat-data:/home/webgoat/.webgoat-8.1.0 webgoat/webgoat-8.0 /home/webgoat/start.sh`

`12:05:18.501 [main] INFO org.owasp.webgoat.StartWebGoat - Starting WebGoat with args: /home/webgoat/start.sh

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
[32m :: Spring Boot :: [39m      [2m (v2.2.2.RELEASE)[0;39m

[2m2020-07-29 12:05:19.385[0;39m [32m INFO[0;39m [35m1[0;39m [2m---[0;39m [2m[           main][0;39m [36morg.owasp.webgoat.StartWebGoat          [0;39m [2m:[0;39m Starting StartWebGoat v8.1.0 on 22c2f7fcf48c with PID 1 (/home/webgoat/webgoat.jar started by webgoat in /home/webgoat)
[2m2020-07-29 12:05:19.386[0;39m [32mDEBUG[0;39m [35m1[0;39m [2m---[0;39m [2m[           main][0;39m [36morg.owasp.webgoat.StartWebGoat          [0;39m [2m:[0;39m Running with Spring Boot v2.2.2.RELEASE, Spring v5.2.2.RELEASE
[2m2020-07-29 12:05:19.387[0;39m [32m INFO[0;39m [35m1[0;39m [2m---[0;39m [2m[           main][0;39m [36morg.owasp.webgoat.StartWebGoat          [0;39m [2m:[0;39m No active profile set, falling back to default profiles: default
[2m2020-07-29 12:05:20.991[0;39m [32m INFO[0;39m [35m1[0;39m [2m---[0;39m [2m[           main][0;39m [36m.s.d.r.c.RepositoryConfigurationDelegate[0;39m [2m:[0;39m Bootstrapping Spring Data JPA repositories in DEFAULT mode.
[2m2020-07-29 12:05:21.139[0;39m [32m INFO[0;39m [35m1[0;39m [2m---[0;39m [2m[           main][0;39m [36m.s.d.r.c.RepositoryConfigurationDelegate[0;39m [2m:[0;39m Finished Spring Data repository scanning in 137ms. Found 2 JPA repository interfaces.
[2m2020-07-29 12:05:21.756[0;39m [32m INFO[0;39m [35m1[0;39m [2m---[0;39m [2m[           main][0;39m [36mtrationDelegate$BeanPostProcessorChecker[0;39m [2m:[0;39m Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[2m2020-07-29 12:05:22.051[0;39m [33m WARN[0;39m [35m1[0;39m [2m---[0;39m [2m[           main][0;39m [36mio.undertow.websockets.jsr              [0;39m [2m:[0;39m UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
[2m2020-07-29 12:05:22.074[0;39m [32m INFO[0;39m [35m1[0;39m [2m---[0;39m [2m[           main][0;39m [36mio.undertow.servlet                     [0;39m [2m:[0;39m Initializing Spring embedded WebApplicationContext
[2m2020-07-29 12:05:22.074[0;39m [32m INFO[0;39m [35m1[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.web.context.ContextLoader           [0;39m [2m:[0;39m Root WebApplicationContext: initialization completed in 2599 ms
[2m2020-07-29 12:05:22.289[0;39m [32m INFO[0;39m [35m1[0;39m [2m---[0;39m [2m[           main][0;39m [36morg.owasp.webgoat.HSQLDBDatabaseConfig  [0;39m [2m:[0;39m Starting internal database on port 9001 ...
[Server@3918c187]: [Thread[main,5,main]]: checkRunning(false) entered
[Server@3918c187]: [Thread[main,5,main]]: checkRunning(false) exited
[Server@3918c187]: [Thread[main,5,main]]: setDatabaseName(0,webgoat)
[Server@3918c187]: [Thread[main,5,main]]: checkRunning(false) entered
[Server@3918c187]: [Thread[main,5,main]]: checkRunning(false) exited
[Server@3918c187]: [Thread[main,5,main]]: setDatabasePath(0,/home/webgoat/.webgoat-8.1.0//data/webgoat)
[Server@3918c187]: [Thread[main,5,main]]: checkRunning(false) entered
[Server@3918c187]: [Thread[main,5,main]]: checkRunning(false) exited
[Server@3918c187]: [Thread[main,5,main]]: setDaemon(true)
[Server@3918c187]: [Thread[main,5,main]]: checkRunning(false) entered
[Server@3918c187]: [Thread[main,5,main]]: checkRunning(false) exited
[Server@3918c187]: [Thread[main,5,main]]: setAddress(127.0.0.1)
[Server@3918c187]: [Thread[main,5,main]]: setTrace(false)
[Server@3918c187]: Initiating startup sequence...
[Server@3918c187]: Server socket opened successfully in 5 ms.
[2m2020-07-29 12:05:22.668[0;39m [31mERROR[0;39m [35m1[0;39m [2m---[0;39m [2m[erver @3918c187][0;39m [36mhsqldb.db.HSQLDB739A767A60.ENGINE       [0;39m [2m:[0;39m could not reopen database

org.hsqldb.HsqlException: Database lock acquisition failure: lockFile: org.hsqldb.persist.LockFile@f1f8aafc[file =/home/webgoat/.webgoat-8.1.0/data/webgoat.lck, exists=false, locked=false, valid=false, ] method: openRAF reason: java.io.FileNotFoundException: /home/webgoat/.webgoat-8.1.0/data/webgoat.lck (No such file or directory)
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	at org.hsqldb.persist.LockFile.newLockFileLock(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	at org.hsqldb.persist.Logger.acquireLock(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	at org.hsqldb.persist.Logger.open(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	at org.hsqldb.Database.reopen(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	at org.hsqldb.Database.open(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	at org.hsqldb.server.Server.openDatabases(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	at org.hsqldb.server.Server.run(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	at org.hsqldb.server.Server.access$000(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	at org.hsqldb.server.Server$ServerThread.run(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]

[Server@3918c187]: [Thread[HSQLDB Server @3918c187,5,main]]: Database [index=0, db=file:/home/webgoat/.webgoat-8.1.0//data/webgoat, alias=webgoat] did not open: org.hsqldb.HsqlException: Database lock acquisition failure: lockFile: org.hsqldb.persist.LockFile@f1f8aafc[file =/home/webgoat/.webgoat-8.1.0/data/webgoat.lck, exists=false, locked=false, valid=false, ] method: openRAF reason: java.io.FileNotFoundException: /home/webgoat/.webgoat-8.1.0/data/webgoat.lck (No such file or directory)
[Server@3918c187]: [Thread[HSQLDB Server @3918c187,5,main]]: Shutting down because there are no open databases
[Server@3918c187]: Initiating shutdown sequence...
[Server@3918c187]: Shutdown sequence completed in 1 ms.
[Server@3918c187]: 2020-07-29 12:05:22.671 SHUTDOWN : System.exit() was not called
[2m2020-07-29 12:05:22.899[0;39m [32m INFO[0;39m [35m1[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.f.c.internal.license.VersionPrinter   [0;39m [2m:[0;39m Flyway Community Edition 6.0.8 by Redgate
[2m2020-07-29 12:05:22.936[0;39m [33m WARN[0;39m [35m1[0;39m [2m---[0;39m [2m[           main][0;39m [36mConfigServletWebServerApplicationContext[0;39m [2m:[0;39m Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyWayContainer' defined in class path resource [org/owasp/webgoat/DatabaseInitialization.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database: java.net.ConnectException: Connection refused (Connection refused)
-------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : -1301
Message    : java.net.ConnectException: Connection refused (Connection refused)

[2m2020-07-29 12:05:22.959[0;39m [32m INFO[0;39m [35m1[0;39m [2m---[0;39m [2m[           main][0;39m [36mConditionEvaluationReportLoggingListener[0;39m [2m:[0;39m 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[2m2020-07-29 12:05:22.963[0;39m [31mERROR[0;39m [35m1[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.boot.SpringApplication              [0;39m [2m:[0;39m Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyWayContainer' defined in class path resource [org/owasp/webgoat/DatabaseInitialization.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database: java.net.ConnectException: Connection refused (Connection refused)
-------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : -1301
Message    : java.net.ConnectException: Connection refused (Connection refused)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
	at org.owasp.webgoat.StartWebGoat.main(StartWebGoat.java:49) ~[classes!/:8.1.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[webgoat.jar:8.1.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[webgoat.jar:8.1.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[webgoat.jar:8.1.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[webgoat.jar:8.1.0]
Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database: java.net.ConnectException: Connection refused (Connection refused)
-------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : -1301
Message    : java.net.ConnectException: Connection refused (Connection refused)

	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60) ~[flyway-core-6.0.8.jar!/:na]
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:80) ~[flyway-core-6.0.8.jar!/:na]
	at org.flywaydb.core.Flyway.execute(Flyway.java:438) ~[flyway-core-6.0.8.jar!/:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:149) ~[flyway-core-6.0.8.jar!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1922) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1864) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	... 28 common frames omitted
Caused by: java.sql.SQLTransientConnectionException: java.net.ConnectException: Connection refused (Connection refused)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677) ~[java.sql:na]
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189) ~[java.sql:na]
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:154) ~[spring-jdbc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:145) ~[spring-jdbc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:205) ~[spring-jdbc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:169) ~[spring-jdbc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56) ~[flyway-core-6.0.8.jar!/:na]
	... 38 common frames omitted
Caused by: org.hsqldb.HsqlException: java.net.ConnectException: Connection refused (Connection refused)
	at org.hsqldb.ClientConnection.openConnection(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	at org.hsqldb.ClientConnection.initConnection(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	at org.hsqldb.ClientConnection.<init>(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	... 48 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:591) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:540) ~[na:na]
	at java.base/java.net.Socket.<init>(Socket.java:436) ~[na:na]
	at java.base/java.net.Socket.<init>(Socket.java:213) ~[na:na]
	at org.hsqldb.server.HsqlSocketFactory.createSocket(Unknown Source) ~[hsqldb-2.5.0.jar!/:2.5.0]
	... 51 common frames omitted
`

**Comment by Sybrid203** [comment]
Managed to fix it by installing portainer and configuring it. Worked like magic :)
