### ISSUE TITLE
cannot bind address

### ISSUE THREAD

**Issue by slothhy** [WebGoat/WebGoat#898]
`[Server@630cb4a4]: [Thread[main,5,main]]: checkRunning(false) entered
[Server@630cb4a4]: [Thread[main,5,main]]: checkRunning(false) exited
[Server@630cb4a4]: [Thread[main,5,main]]: setDaemon(true)
[Server@630cb4a4]: [Thread[main,5,main]]: checkRunning(false) entered
[Server@630cb4a4]: [Thread[main,5,main]]: checkRunning(false) exited
[Server@630cb4a4]: [Thread[main,5,main]]: setAddress(127.0.0.1)
[Server@630cb4a4]: [Thread[main,5,main]]: setTrace(false)
[Server@630cb4a4]: Initiating startup sequence...
[Server@630cb4a4]: [Thread[HSQLDB Server @630cb4a4,5,main]]: run()/openServerSocket():
java.net.BindException: Address already in use: bind
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:550)
        at java.base/sun.nio.ch.Net.bind(Net.java:539)
        at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:396)
        at java.base/java.net.ServerSocket.<init>(ServerSocket.java:282)
        at org.hsqldb.server.HsqlSocketFactory.createServerSocket(Unknown Source)
        at org.hsqldb.server.Server.openServerSocket(Unknown Source)
        at org.hsqldb.server.Server.run(Unknown Source)
        at org.hsqldb.server.Server.access$000(Unknown Source)
        at org.hsqldb.server.Server$ServerThread.run(Unknown Source)
[Server@630cb4a4]: Initiating shutdown sequence...
Exception in thread "HSQLDB Server @630cb4a4" java.lang.NullPointerException: Cannot invoke "java.lang.ThreadGroup.activeCount()" because "this.serverConnectionThreadGroup" is null
        at org.hsqldb.server.Server.shutdown(Unknown Source)
        at org.hsqldb.server.Server.run(Unknown Source)
        at org.hsqldb.server.Server.access$000(Unknown Source)`

I can't start the server, tried multiple ports

**Comment by zubcevic** [comment]
The information provided is very limited. But I still think what happened.
You try to run it as a standalone java application. Either from the download or from a custom build.
A default standalone WebGoat takes ports 8080 and 9001. And a WebWolf additionally 9090.

Probably you focussed on changing 8080, but the 9001 might be in use.
Checkout: https://github.com/WebGoat/WebGoat/blob/develop/webgoat-container/src/main/resources/application-webgoat.properties 

You can use environment variables to override the defaults. So before starting java:
on Windows:
set WEBGOAT_PORT=18080
set WEBGOAT_HSQLPORT=19001

or on Linux/Mac

export WEBGOAT_PORT=18080
export WEBGOAT_HSQLPORT=19001
